### ISSUE TITLE
Create New Address Form - Full Address Field - Hyphen

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#10]
Requirement: Entering a hyphen between two whole numbers should result in the first number being transferred to the base field and the second number being transferred to the high field.
When a hyphen is included the full address field does not transform at all.

**Comment by SPlanzer** [comment]
Implemented - Please test in next version

**Comment by Deb-Jones** [comment]
Error has been fixed.

**Comment by Deb-Jones** [comment]
Reopened because further testing found the format 300-312 now correctly transfers to 300 in the base field and 312 in the high field. But 1/300-312 does not transform at all. It should transform to 1 in the unit field, 300 in the base field and 312 in the high field.

**Comment by SPlanzer** [comment]
now handling  1/300-312 and  G101/300-312 

Please test in release 0.1.28

**Comment by Deb-Jones** [comment]
All tested examples transform.
