### ISSUE TITLE
Water Name is a required API field

### ISSUE THREAD

**Issue by SPlanzer** [linz/QGIS-AIMS-Plugin#100]
issue split from #59

If I attempt to add a water route address I get a pop-up error in the UI stating: WaterName must be provided.

**Comment by SPlanzer** [comment]
As I understand it the "waterName" is calculated by the API.

If this is correct an issue must be opened against the API/DB to remove the validation rule that requires this property/value to be supplied to the API

If my understanding is correct should the "waterName" even be in new / editing feature forms? or will the user at times override the API calculated waterName?

**Comment by e-spatial** [comment]
I'll check into this too

**Comment by Deb-Jones** [comment]
For address add the current functionality is acceptable.

Users will have to enter free text the water name associated to the water route. This should be reviewed in 1.1 along with the requirements around water name vs locality.
