### ISSUE TITLE
External Object Id Scheme not passed to API

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#104]
The ext Object Id Scheme is not passed to the API on an address add.

**Comment by Deb-Jones** [comment]
We have a field in the UI for External Object Id and Ext Object Id Scheme.

External Object Id is actually the Addressable Object Id, i.e. the parcel ID. It doesn't matter what we enter in the UI, it is overwritten with the point-in-polygon parcel ID.

If you select Object Type Building, you get an error stating:
• AddressPosition is mandatory for a Building AddressableObject
• AddressableObjectID cant be assigned using the spatial Address object

So an addressable object requires a geometry.

If we are happy with this functionality, we need to remove Addressable Object Type, External Object ID and External Object Id Scheme from the UI.

The other option is to recognise External Object Id as a separate parameter to the Addressable Object, which I believe would be a big job.

**Comment by linzbjones** [comment]
Discussed and solved
