### ISSUE TITLE
Move Stacked Address

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#105]
When I select to move an address out of a stack, regardless of which address I select from the Select feature to update form, the first feature is moved.

If I select more than one address from the stack, it tries to move the first address multiple times.

**Comment by SPlanzer** [comment]
Please retest in 0.8.11

**Comment by Deb-Jones** [comment]
Closed pending testing

**Comment by Deb-Jones** [comment]
tested, passed
