### ISSUE TITLE
Road Name Components should be non-editable on a modify

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#108]
The road name components should be non-editable through the UI on a modify. This is because the value in the rcl_id will be used by the API and any changes entered into the road name component fields will be ignored. It is misleading to allow them to be edited.

This was discussed earlier in development but not documented at that time.

**Comment by Deb-Jones** [comment]
Also, Water Route name should be non-editable on a modify and a modify during QA.

All road name components should be non-editable for a modify during QA.

**Comment by SPlanzer** [comment]
Please retest in 0.8.11

**Comment by SPlanzer** [comment]
Please retest in 0.8.11

**Comment by Deb-Jones** [comment]
passed
