### ISSUE TITLE
Create New Address Form - Number Prefix field - Case

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#11]
Requirement: Alphas in the number prefix field should be converted to upper case when the address is submitted.
This requirement was not advised prior to development and was not developed.

**Comment by SPlanzer** [comment]
Implemented - Please test in next version

**Comment by Deb-Jones** [comment]
Alpha prefixes entered in lower case in UI now pass to API upper cased.
