### ISSUE TITLE
RCL Id should be non-editable during QA edit

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#110]
During QA edit, it is possible to overtype the RCL Id. This should be non-editable like it is in the Edit Feature form.

**Comment by SPlanzer** [comment]
OK, Done

Please review in 0.8.11

**Comment by Deb-Jones** [comment]
Tested, RCL Id is still editable.

**Comment by SPlanzer** [comment]
This was resolved but I see with other conditions since added concerning field read/write it get over written.

I have talked with @Deb-Jones and since hardcoded for rclID to always be readonly

**Comment by Deb-Jones** [comment]
Tested, passed.
