### ISSUE TITLE
Error not generated when object type is updated in QA edit mode.

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#113]
When the Object Type is changed from Parcel to Building in QA edit mode, the AddressableObjectID can't be assigned using the spatial Address object error is not generated. The address change can be accepted and the address is published with an object type of building.

The address can then not be moved or edited because at the point that you move or edit it you get the AddressableObjectID can't be assigned using the spatial Address object error.

You do get the error if you modify an address. You don't get it if you modify in QA.

**Comment by SPlanzer** [comment]
Hi @Deb-Jones, More information below. I am handing this one back to you. As you can see below when submitting an update to the changefeed the response is a Error. However when submitting the update to the resolutionfeed the API does not return a error and update to the objectType property is performed. 

It seems to me we can either:
- Alter the API to return a Error
- Alter the UI to disallow this (not ideal as future clients will then have the same issues)
- Remove "building" from the UI and add support for buildings at a later date
- ...?

**Update Changefeed (Parcel --> Building)**

PAYLOAD

> {'version': 75633, 'addressedObject': {'addressPositions': [{'position': {'crs': {'type': u'name', 'properties': {'name': u'urn:ogc:def:crs:EPSG::4167'}}, 'type': u'Point', 'coordinates': [168.1347977, -46.8863184167]}, 'positionType': u'Unknown', 'primary': True}], **'objectType': u'Building'**}, 'components': {'addressType': u'Road', 'addressId': 82792, 'roadName': u'Horseshoe Bay', 'roadType': u'Road', 'roadCentrelineId': u'25916', 'suburbLocality': u'Stewart Island/Rakiura', 'addressNumber': u'178', 'townCity': u'Stewart Island', 'lifecycle': u'Current'}, 'workflow': {'sourceUser': 'splanzer'}}

RESPONSE 

properties

> dict: {u'status': 400, u'reason': u'Bad Request', u'message': u'Validation Errors'}

entities 

> <type 'list'>: [{u'class': [u'validation'], u'rel': [u'error'], u'properties': {u'severity': u'Reject', u'description': u'AddressableObjectID cant be assigned using the spatial Address object', u'ruleId': u'AIMS: V0027'}}]

**Update Resolutionfeed (parcel --> building)**

PAYLOAD

> {'version': 398250, 'addressedObject': {'addressPositions': [{'position': {'crs': {'type': u'name', 'properties': {'name': u'urn:ogc:def:crs:EPSG::4167'}}, 'type': u'Point', 'coordinates': [168.12986936667, -46.8819076833]}, 'positionType': u'Unknown', 'primary': True}], 'externalObjectId': u'7037951', 'objectType': u'Building'}, 'components': {'addressType': u'Road', 'roadName': u'Horseshoe Bay', 'suburbLocality': u'Stewart Island/Rakiura', 'roadCentrelineId': u'20865', 'roadType': u'Road', 'addressNumber': u'239', 'townCity': u'Stewart Island', 'lifecycle': u'Current'}, 'changeId': 3524595}

RESPONSE 

properties

> {u'addressedObject': {u'addressPositions': [{u'position': {u'crs': {u'type': u'name', u'properties': {u'name': u'urn:ogc:def:crs:EPSG::4167'}}, u'type': u'Point', u'coordinates': [168.12986936667, -46.8819076833]}, u'positionType': u'Unknown', u'primary': True}], u'externalObjectId': u'7037951', u'objectType': u'Building'}, u'workflow': {u'reviewedUserName': u'splanzer', u'submittedDate': u'2016-06-23', u'reviewedDate': u'2016-06-27', u'submitterUserName': u'splanzer', u'queueStatus': u'Under Review', u'sourceOrganisation': u'LINZ'}, u'changeType': u'Update', u'changeId': 3524595, u'version': 402952, u'components': {u'addressType': u'Road', u'addressId': 82746, u'roadName': u'Horseshoe Bay', u'suburbLocality': u'Stewart Island/Rakiura', u'roadCentrelineId': 20865, u'roadType': u'Road', u'addressNumber': 239, u'townCity': u'Stewart Island', u'lifecycle': u'Current'}}

entities

> <type 'list'>: []

**Comment by Deb-Jones** [comment]
Replaced by https://github.com/linz/AIMS/issues/123
