### ISSUE TITLE
Modify Address - High not being recorded.

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#114]
When I modify an address and add a high number, it does not appear on the review queue.
When I modify an address in QA and add a high number, it does appear.

@SPlanzer can you please check whether this is a UI or an API/DB issue?

**Comment by SPlanzer** [comment]
class factory template (update) has now had "addressNumberHigh":None added

Please retest in 0.8.11

**Comment by Deb-Jones** [comment]
Closed pending testing

**Comment by Deb-Jones** [comment]
tested, passed
