### ISSUE TITLE
Hide Appellation, Certificate of Title and Valuation Ref

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#115]
Hide Appellation, Certificate of Title and Valuation Ref from the feature form and the edit QA form.

https://github.com/linz/AIMS/issues/114
The API/DB has not been built for this function and has been deferred to milestone 1.1.

**Comment by SPlanzer** [comment]
Appellation, Certificate of Title and Valuation Ref inputs and labels now have had a .hide() executed against them

Please review in 0.8.11

**Comment by Deb-Jones** [comment]
tested. passed.
