### ISSUE TITLE
Import CSV

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#117]
We are planning on using the standard QGIS add delimited text layer tool.

This tool does not give you the option to convert geometry. You can only select which field holds the x value and which field holds the y value.

Most of our files are received in EPSG:2193 but we're working in EPSG:4167.

To import a csv, you need to convert the geometries to 4167 first.

**Comment by dwsilk** [comment]
1. Add layer to QGIS using Add Delimited Text Layer tool
2. Right click layer > Set Layer CRS. Set it to the source CRS, e.g. EPSG:2193.
3. Right click layer > Save as shapefile using EPSG:2193.
4. Right click new layer > Save as shapefile using EPSG:4167.

I think that is how you do it. Maybe Step 3 can be skipped, I don't have a CSV on hand to test with.

**Comment by Deb-Jones** [comment]
I've attached an example CSV.

[WCC20160620.txt](https://github.com/linz/QGIS-AIMS-Plugin/files/338281/WCC20160620.txt)

**Comment by dwsilk** [comment]
1. Change Project CRS to source CRS of CSV
2. Add layer to QGIS using Add Delimited Text Layer tool
3. Change Project CRS back to EPSG:4167

..seems to work.

**Comment by dwsilk** [comment]
But maybe there is a better way. Under Settings > Options > CRS, change the `CRS for new layers` setting to `Prompt for CRS`.

Then you can provide the source CRS after using the Add Delimited Text Layer tool.
