### ISSUE TITLE
Create New Address Form - Unit Value field - Case

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#12]
Requirement: Alphas in the unit value field should be converted to upper case when the address is submitted.
This requirement wasn't communicated prior to development and was not developed.

**Comment by SPlanzer** [comment]
Implemented - Please test in next version

**Comment by Deb-Jones** [comment]
Unit value alphas entered lower case in UI are passed to API in upper case.
