### ISSUE TITLE
Edit Water Address in QA Failing Yellow Banner Error

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#121]
Edit a water address, it appears on the review queue.
Edit a different value on the review queue and select Update.

Yellow banner error produced.

![image](https://cloud.githubusercontent.com/assets/15723101/16436895/fcb0fe42-3df5-11e6-81e2-e94139d8e6d9.png)

**Comment by SPlanzer** [comment]
No Water features would have been update-able at review. Change to Feature Factory template has resolved this

Please retest in 0.8.12

**Comment by Deb-Jones** [comment]
Tested, passed.
