### ISSUE TITLE
Parcels Missing from UI

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#123]
Since API/DB 1.0.1 was rolled out, parcels have disappeared from the UI.

**Comment by linzbjones** [comment]
TWG - 06/07/16 - @SPlanzer @dwsilk  review permissions

**Comment by Deb-Jones** [comment]
Testing by bringing in the BDE parcels as a contextual layer.

**Comment by Deb-Jones** [comment]
Can wait for @SPlanzer to come back to fix. Not stopping testing.

**Comment by josephramsay** [comment]
view permissions had been changed, should be fixed now

**Comment by Deb-Jones** [comment]
Fixed.
