### ISSUE TITLE
Python Error when review queue empty

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#124]
When all items on the review queue are accepted, accepting the last item generates a python error and the item stays on the queue.

An error has occurred while executing Python code:

Traceback (most recent call last):
  File "D:/Users/djjones/.qgis2/python/plugins\aims\AimsUI\AimsClient\Gui\ReviewQueueWidget.py", line 216, in featureSelected
    self.uQueueEditor.currentFeatureToUi(self.currentReviewFeature())
  File "D:/Users/djjones/.qgis2/python/plugins\aims\AimsUI\AimsClient\Gui\QueueEditorWidget.py", line 87, in currentFeatureToUi
    UiUtility.featureToUi(self, 'r'+self.feature._changeType)
AttributeError: 'NoneType' object has no attribute '_changeType'

Python version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

QGIS version:
2.8.7-Wien Wien, 8a47921

Python path: ['D:/Users/djjones/.qgis2/python/plugins\processing', 'D:\Users\djjones\.qgis2\python\plugins\aims', 'G:/QGIS28/apps/qgis-ltr/./python', u'D:/Users/djjones/.qgis2/python', u'D:/Users/djjones/.qgis2/python/plugins', 'G:/QGIS28/apps/qgis-ltr/./python/plugins', 'C:\Program Files (x86)\ArcGIS\bin', 'G:\QGIS28\bin\python27.zip', 'G:\QGIS28\apps\Python27\DLLs', 'G:\QGIS28\apps\Python27\lib', 'G:\QGIS28\apps\Python27\lib\plat-win', 'G:\QGIS28\apps\Python27\lib\lib-tk', 'G:\QGIS28\bin', 'G:\QGIS28\apps\Python27', 'G:\QGIS28\apps\Python27\lib\site-packages', 'G:\QGIS28\apps\Python27\lib\site-packages\PIL', 'G:\QGIS28\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win32.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\python_dateutil-2.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\pytz-2014.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\win32', 'G:\QGIS28\apps\Python27\lib\site-packages\win32\lib', 'G:\QGIS28\apps\Python27\lib\site-packages\Pythonwin', 'G:\QGIS28\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win32.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\six-1.10.0-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', u'D:/Users/djjones/.qgis2//python', '..', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', 'D:\Users\djjones\.qgis2\python\plugins\intramaps_qgis\ui', '.', 'G:\QGIS28\apps\qgis-ltr\python\plugins\ElectoralAddressPlugin', 'G:\QGIS28\apps\qgis-ltr\python\plugins\fTools\tools', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc']

**Comment by josephramsay** [comment]
wrote bypass on null feature, @splanzer to package

**Comment by SPlanzer** [comment]
Please tested in 0.8.13
