### ISSUE TITLE
Road Prefix Not Displaying in Review Queue

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#125]
Road Prefix is not displaying in the review queue.

It does appear in aims_stage.change_address.
After acceptance, it does appear in aims_stage.address_publish.
There is no error regarding prefix in aims_stage.change_validation.

In the resolution feed browser, it is visible:
 "roadPrefix":"Upper",
 "roadName":"Bartlett",
 "roadType":"Grove",

**Comment by SPlanzer** [comment]
Resolved.  Please retest in 0.8.13

**Comment by Deb-Jones** [comment]
Tested 0.8.16 Passed.
