### ISSUE TITLE
Number splitter field does not recognise alpha numeric units

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#126]
Enter 1A/10

Should create Unit 1A, Base 10.
Individual components not populated.

Other combinations seem to work.

**Comment by SPlanzer** [comment]
Fixed as to split above example. 

It is expected however some edge cases may not be split and the user will need to populated the individual components by hand

Please test in 0.8.13

**Comment by Deb-Jones** [comment]
Tested 0.8.16. Passed.
