### ISSUE TITLE
External Address Id Field Limited to 9 numeric

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#128]
The External Address Id field is limited to 9 numbers in the UI Edit Feature Form (during add).

This value is passed to the aims_stage.change_address.externalid field, which is character varying(15). The UI field should allow alpha and numeric up to 15 characters.

**Comment by SPlanzer** [comment]
Please retest in 0.8.13

**Comment by Deb-Jones** [comment]
Tested 0.8.16 Passed.
