### ISSUE TITLE
Error Message Closing Feature Form

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#130]
When I enter a meshblock override of 8 characters I get a pop up warning that Meshblock override should be 7 characters.

When I click OK, the feature form closes and I've lost the details I've entered for my address add.

**Comment by SPlanzer** [comment]
Resolved by limiting input to max length 7

Also limited to integers only

**Comment by Deb-Jones** [comment]
Tested 0.8.16 Passed.
