### ISSUE TITLE
Deploy API/Database to Dev

### ISSUE THREAD

**Issue by SPlanzer** [linz/QGIS-AIMS-Plugin#133]
Ideally the Database / API would be deployed to DEV to allow development to proceed without disrupting testing. 

For example: Deb has opened an issue (#124) whereby the implemented fix needs to be tested against an empty queue. Removing all data from the queue to test this may disrupt UAT

**Comment by billgeo** [comment]
TWG: @josephramsay can you please do this today so Shane and other can use for bug triage.

**Comment by josephramsay** [comment]
Nope. Last deploy took 6 hours. On a non-cleaned database it will take longer. I certainly won't be able to do it without @shane-turk-espatial overseeing. Will start tomorrow

**Comment by shane-turk-espatial** [comment]
I have yet to go through the TST environment to create UTIL scripts to delete roles and users etc.

**Comment by josephramsay** [comment]
users/roles and permissions differ between tst1 and dev1

**Comment by billgeo** [comment]
As discussed, can @SPlanzer have a crack at this tomorrow with support from @josephramsay.

**Comment by dwsilk** [comment]
I missed this issue. Seems like this includes data migration and if so, roads still need to be deployed first.

Is there a faster option to keep tst and dev in sync e.g. pg_dump from tst / restore to dev after each migration. Could we do a pg_dump / restore now to solve Simon's issue? I realise API is separate but can that be reinstalled independent of a full deployment?

**Comment by SPlanzer** [comment]
Done
