### ISSUE TITLE
Water Name needs to be editable on an update

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#134]
If the user changes a road address to be a water address, there will be no value in the water name. So when they submit the change, they will get an error saying that the water name is required.

For Update and Update in QA the water name needs to be editable.

This problem was caused because I requested the road name fields to be non-editable on updates.

**Comment by SPlanzer** [comment]
water name now editable on all updates

**Comment by Deb-Jones** [comment]
Tested 0.8.16 Passed.
