### ISSUE TITLE
Review Queue Selection

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#135]
When a user filters on their changes only, after accepting a change, the selection moves to the next item on the queue even if it's not their item. So the top panel shows nothing selected, the middle panel shows the next items details (not theirs).

This is a low priority issue.

**Comment by Deb-Jones** [comment]
Causing users confusion. Would be good to fix before go live if we can.

**Comment by SPlanzer** [comment]
Please Retest in 0.8.13

**Comment by Deb-Jones** [comment]
Tested 0.8.16. Not fixed.

**Comment by SPlanzer** [comment]
I can not reproduce.@Deb-Jones  Can you provide your work flow?

**Comment by SPlanzer** [comment]
Resolved
