### ISSUE TITLE
Accepting a reference data group review tab job does nothing

### ISSUE THREAD

**Issue by billgeo** [linz/QGIS-AIMS-Plugin#138]
See attached. Hitting the 'Accept' button does nothing. Might be user error.
Need to clear this queue item to run the reference data UAT tests.

![screenshot from 2016-07-12 17 24 20](https://cloud.githubusercontent.com/assets/8991188/16755974/c464f7ae-4855-11e6-81c3-4a52ec6c96e7.png)

**Comment by SPlanzer** [comment]
Fixed on UI end.

Waiting for [#146](https://github.com/linz/AIMS/issues/146) to test

**Comment by Deb-Jones** [comment]
Closed pending testing

**Comment by Deb-Jones** [comment]
Tested. Passed.
