### ISSUE TITLE
Create wiki page or similar for test approach/coverage

### ISSUE THREAD

**Issue by billgeo** [linz/QGIS-AIMS-Plugin#139]
As per [AIMS repo](https://github.com/linz/AIMS/wiki/Test-Coverage), can you please document (automatically if possible) what testing is and isn't being done for this repo and what coverage there is. This doesn't have to be to to the nth degree, but someone like me should be able to read it and determine how much of the system is being tested.

**Comment by SPlanzer** [comment]
Created a test coverage [page](https://github.com/linz/QGIS-AIMS-Plugin/wiki/Test-Coverage) similar to ES. The focus is on UAT
