### ISSUE TITLE
Unable to link address to an addressable object it doesn't sit within

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#141]
Test:

![image](https://cloud.githubusercontent.com/assets/15723101/16791127/f11da8c6-490f-11e6-8d0e-6a2d053dc24d.png)

5 Zion Way is in parcelid 4285727, addressableobjectid 1115135.
7 Zion Way is in parcelid 4434062, addressableobjectid 2479989.

I created 5A Zion Way in parcelid 4285727, but entered 2479989 into the Ext. Obj Id.

It was published as:
5A Zion Way is in parcelid 4285727, addressableobjectid 1115135.

I am assuming (maybe incorrectly) that Simon needs to add the addressableobjectid to the UI. It is in the feature feed.

If yes, what is the function of the External Object Id?

**Comment by Deb-Jones** [comment]
I will defer this to milestone 1.1 (i.e. post-go-live) because we need this change in order to test functionality that should have been delivered in the API/DB, but we won't be using this function at go-live.
There are further details to be considered. The details encountered with meshblock override are an indication of the type of details to be worked through.

**Comment by rgabara** [comment]
TWG - reassigned to Ben while Bill is off project

**Comment by Deb-Jones** [comment]
This is not the intended functionality. Addressable Object assignment is intended to be point-in-polygon. Any type of Addressable Object will require a polygon and the addressableobjectid will be calculated based on the position of the address point.

Any choice in addressable object would be different types of addressable object having overlapping polygons. In which case the addressableobjectid would be calculated based on the object type and position.
