### ISSUE TITLE
Create New Address form - Alpha field - Case

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#15]
Requirement: Alphas in the Alpha field (addressNumberSuffix) must be upper case when submitted to the database.
This requirement was not advised prior to development and was not developed.

**Comment by SPlanzer** [comment]
Implemented - Please test in next version

**Comment by Deb-Jones** [comment]
Alphas entered in lower case in UI submitted to API in upper case.
