### ISSUE TITLE
Appellation is populated but does not update when its spatial relationship between feature and parcel changes

### ISSUE THREAD

**Issue by SPlanzer** [linz/QGIS-AIMS-Plugin#150]
This is related to the [114 fix](https://github.com/linz/AIMS/issues/114)

It seems in the recent data migration all AIMS features have had an appellation populated that represents the AIMS feature to parcel relationship. 

This is also true for the Addressable Object Id that is populate with the parcel ID.

When a AIMS Feature is moved the Addressable Object Id (the parcel Id) is recalculated. This is not the case with the appellation and thus when a point is moved the stored appellation reflects the point/poly relationship at the time of migration and not the true modified spatial relationship

Options?:
- After a move the user performs a feature update and manually inputs the new appellation
- The UI calculates the new Appellation.
- The API calculates the new Appellation
- The data migration does not populate the Appellation property and the Appellation is calculated as needed.

**Comment by SPlanzer** [comment]
I have made this a question, added many (Assignees) and I am looking for comment

**Comment by linzbjones** [comment]
@e-spatial @SPlanzer @Deb-Jones can we please discuss this at the TWG meeting on Monday.

**Comment by Deb-Jones** [comment]
We need a discussion about what these fields are for and how we expect them to perform. This includes:
External Address Id
Object Name
External Object Id
Valuation Reference
Certificate of Title
Appellation
We need to clarify the business requirement prior to the TWG meeting.

**Comment by rgabara** [comment]
TWG - need to understand this in detail. Workshop Deb, Simon, Ben, Shane and Pete- @linzbjones to arrange.

**Comment by Deb-Jones** [comment]
Refer to https://github.com/linz/AIMS/issues/157.

The appellation will no longer be populated during data migration. Any value a user enters into this field will be free text and if it is populated by a user, then it's the responsibility of any user editing this address to maintain it's accuracy.
