### ISSUE TITLE
Slow Performance due to BDE

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#151]
The server is running at 90% when I'm not doing anything.

I have QGIS and PgAdmin open, but I'm not running any queries and I'm not doing anything in QGIS. (i.e. not even panning the map).

When I do start making edits to addresses responses are extremely slow and I'm regularly getting a time out problem or a data refresh problem.

The BDE is running on the server.

This means that I can't test because the server capacity issue is bringing up errors that I then have to retest and results aren't consistent.

**Comment by linzbjones** [comment]
@SPlanzer Is there anyone that can stop the BDE from running so Deb can test?

**Comment by palmerj** [comment]
@linzbjones I've stopped it, then restarted it to complete faster. Should be up-to-date by Saturday morning if the update works correctly.

**Comment by palmerj** [comment]
linz_db database on tstassgeo01 is now up-to-date with BDE data. It should run as normal tomorrow and be available for testing from midday. Please re-open this issue if the problem persists. We should consider turning off the "Public LDS full BDE" update part of the process as this is not needed for AIMS, only LDS. This is dependant on the outcome of @SPlanzer question on  https://github.com/linz/LI-tasks/issues/35
