### ISSUE TITLE
Hide External Object Id and External Object Id Scheme from the UI.

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#154]
Refer to database issue https://github.com/linz/AIMS/issues/157.

The External Object Id and External Object Id Scheme should be calculated using the object type and position of the address point.

Users should not interact with External Object Id or External Object Id Scheme. Therefore these should be hidden from the UI.

**Comment by SPlanzer** [comment]
Done. please expect changes in 0.8.17

**Comment by Deb-Jones** [comment]
Tested 0.8.17. Passed.
