### ISSUE TITLE
Refresh resets QA Edit Values

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#157]
When you update values in QA Edit, if a refresh occurs all the values are reset and you loose your changes.

This would occur in BAU if you were interrupted and didn't enter Update before the refresh.

**Comment by linzbjones** [comment]
TWG - needs to be scoped and reassessed.

**Comment by rgabara** [comment]
TWG - @SPlanzer  please provide an update

**Comment by SPlanzer** [comment]
Ready for @Deb-Jones  to test
