### ISSUE TITLE
Meshblock Override for hole in meshblock

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#159]
@linzbjones  Meshblock overrides get applied when you accept a change. Validation occurs when you submit a change.

So placing an address point outside all meshblocks, but entering a meshblock override still triggers validation rule 56 "Address does not fall within a meshblock";"Info";t.

I had thought the correct functionality was for validation rule 56 not to trigger if there is a meshblock override.

I think it is OK for validation rule 56 to be triggered. The address_publish table still gets the meshblock override value and a flag to say it's an override. So published data will have a meshblock. Also, it's an Info so you can still accept the change.

Do you agree that this is OK?

**Comment by linzbjones** [comment]
@Deb-Jones it sounds ok to me. Definitely not a high priority
