### ISSUE TITLE
Create New Address Form - Appellation - not passed to API

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#16]
When appellation field is populated, the appellation does not pass through to the API.

**Comment by SPlanzer** [comment]
Implemented - please test in next version

**Comment by Deb-Jones** [comment]
Appellation field in UI now populates Certificate of Title field. Certificate of Title field in UI doesn't seem to populate anything.

**Comment by SPlanzer** [comment]
fixed, please test in release 0.1.28

**Comment by Deb-Jones** [comment]
Retested. Successful.
