### ISSUE TITLE
Python Error when accepting the same change twice

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#162]
I was accepting items on the review queue. The top item looked like it hadn’t been accepted so I went back up and accepted it again. I got a conflict id message pop up, but then this python error popped up.

I've only seen it once so not sure how to replicate it.

An error has occurred while executing Python code:
Traceback (most recent call last):
  File "D:/Users/djjones/.qgis2/python/plugins\aims\AimsUI\AimsClient\Gui\ReviewQueueWidget.py", line 221, in featureSelected
    self.uQueueEditor.currentFeatureToUi(self.currentReviewFeature())
  File "D:/Users/djjones/.qgis2/python/plugins\aims\AimsUI\AimsClient\Gui\QueueEditorWidget.py", line 91, in currentFeatureToUi
    UiUtility.featureToUi(self, 'r'+self.feature._changeType)
  File "D:/Users/djjones/.qgis2/python/plugins\aims\AimsUI\AimsClient\Gui\UiUtility.py", line 207, in featureToUi
    elif hasattr(getattr(getattr(self.feature, 'meta'), '_entities')[0],objProp[0]):
IndexError: list index out of range

Python version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

QGIS version:
2.8.7-Wien Wien, 8a47921

Python path: ['D:/Users/djjones/.qgis2/python/plugins\processing', 'D:\Users\djjones\.qgis2\python\plugins\aims', 'G:/QGIS28/apps/qgis-ltr/./python', u'D:/Users/djjones/.qgis2/python', u'D:/Users/djjones/.qgis2/python/plugins', 'G:/QGIS28/apps/qgis-ltr/./python/plugins', 'C:\Program Files (x86)\ArcGIS\bin', 'G:\QGIS28\bin\python27.zip', 'G:\QGIS28\apps\Python27\DLLs', 'G:\QGIS28\apps\Python27\lib', 'G:\QGIS28\apps\Python27\lib\plat-win', 'G:\QGIS28\apps\Python27\lib\lib-tk', 'G:\QGIS28\bin', 'G:\QGIS28\apps\Python27', 'G:\QGIS28\apps\Python27\lib\site-packages', 'G:\QGIS28\apps\Python27\lib\site-packages\PIL', 'G:\QGIS28\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win32.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\python_dateutil-2.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\pytz-2014.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\win32', 'G:\QGIS28\apps\Python27\lib\site-packages\win32\lib', 'G:\QGIS28\apps\Python27\lib\site-packages\Pythonwin', 'G:\QGIS28\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win32.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\six-1.10.0-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', u'D:/Users/djjones/.qgis2//python', '..', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', 'D:\Users\djjones\.qgis2\python\plugins\intramaps_qgis\ui', '.', 'G:\QGIS28\apps\qgis-ltr\python\plugins\ElectoralAddressPlugin', 'G:\QGIS28\apps\qgis-ltr\python\plugins\fTools\tools', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc']

**Comment by SPlanzer** [comment]
Having difficulty replicating. Will explore further this week

**Comment by SPlanzer** [comment]
Hi @Deb-Jones, I haven't been able to recreate this. Have you been seen this since?

If so, could you please add the trace back each time so that we can track the frequency.

**Comment by linzbjones** [comment]
@Deb-Jones do you have an update on recreating this and is it still low priority

**Comment by Deb-Jones** [comment]
Haven't seen it again.

**Comment by SPlanzer** [comment]
I have spent half an hour today trying to recreate this without success. This afternoon, based on the trace back I will investigate what i can do to add further resilience here

**Comment by Deb-Jones** [comment]
I accepted the same change twice and got an error message. This is acceptable.

**Comment by Deb-Jones** [comment]
I accepted the same change twice today and got a python error again.

An error has occurred while executing Python code:

Traceback (most recent call last):
  File "D:/Users/djjones/.qgis2/python/plugins\aims\AimsUI\AimsClient\Gui\ReviewQueueWidget.py", line 225, in featureSelected
    self.uQueueEditor.currentFeatureToUi(self.currentReviewFeature())
  File "D:/Users/djjones/.qgis2/python/plugins\aims\AimsUI\AimsClient\Gui\QueueEditorWidget.py", line 111, in currentFeatureToUi
    UiUtility.featureToUi(self, 'r'+self.feature._changeType)
  File "D:/Users/djjones/.qgis2/python/plugins\aims\AimsUI\AimsClient\Gui\UiUtility.py", line 244, in featureToUi
    posType = self.feature._addressedObject_addressPositions[0]._positionType
AttributeError: 'AddressResolution' object has no attribute '_addressedObject_addressPositions'

Python version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

QGIS version:
2.8.7-Wien Wien, 8a47921

Python path: ['D:/Users/djjones/.qgis2/python/plugins\processing', 'D:\Users\djjones\.qgis2\python\plugins\aims', 'G:/QGIS28/apps/qgis-ltr/./python', u'D:/Users/djjones/.qgis2/python', u'D:/Users/djjones/.qgis2/python/plugins', 'G:/QGIS28/apps/qgis-ltr/./python/plugins', 'C:\Program Files (x86)\ArcGIS\bin', 'G:\QGIS28\bin\python27.zip', 'G:\QGIS28\apps\Python27\DLLs', 'G:\QGIS28\apps\Python27\lib', 'G:\QGIS28\apps\Python27\lib\plat-win', 'G:\QGIS28\apps\Python27\lib\lib-tk', 'G:\QGIS28\bin', 'G:\QGIS28\apps\Python27', 'G:\QGIS28\apps\Python27\lib\site-packages', 'G:\QGIS28\apps\Python27\lib\site-packages\PIL', 'G:\QGIS28\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win32.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\python_dateutil-2.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\pytz-2014.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\win32', 'G:\QGIS28\apps\Python27\lib\site-packages\win32\lib', 'G:\QGIS28\apps\Python27\lib\site-packages\Pythonwin', 'G:\QGIS28\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win32.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\six-1.10.0-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', u'D:/Users/djjones/.qgis2//python', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '..', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', 'D:\Users\djjones\.qgis2\python\plugins\intramaps_qgis\ui', 'G:\QGIS28\apps\qgis-ltr\python\plugins\ElectoralAddressPlugin', 'G:\QGIS28\apps\qgis-ltr\python\plugins\fTools\tools', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc']

**Comment by Deb-Jones** [comment]
Not seen since go-live. Close issue and reopen if it reoccurs.
