### ISSUE TITLE
Display of Full Road in QA Queue Detail

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#165]
![image](https://cloud.githubusercontent.com/assets/15723101/17280806/617bc12e-57e9-11e6-91e0-bbea4d015cb1.png)

Water Name is currently displayed in the Full Road Name field. Please display it in the Locality field.

**Comment by SPlanzer** [comment]
Removed from road name. Still need to map water name to localities

**Comment by SPlanzer** [comment]
I have stripped out the Water Name from the Full Road but have not mapped it to the locality.

Therefore when a Water Address is shown in the feature table the Water Route is shown in the Full Road. Water Name is not mapped to the locality but is shown in the detailed address view. 

I am going defer the mapping to Water Name to Locality in the feature table view until 1.1 as it would be risky to modify the under lying table data structure going into the final UAT and this risk would be for little benefit.
