### ISSUE TITLE
After plugin unload bbox trigger still called

### ISSUE THREAD

**Issue by SPlanzer** [linz/QGIS-AIMS-Plugin#167]

**Comment by SPlanzer** [comment]
Resolved

**Comment by linzbjones** [comment]
TWG - @SPlanzer  has this been resolved and implemented?

**Comment by SPlanzer** [comment]
This has been implemented but there are still potentially unload issues  that manifest as crash reports only in Windows environments. 

I have open a new issue to capture this -  #181
