### ISSUE TITLE
Review Queue Items displaying incorrectly

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#169]
Simon to document detail.

**Comment by billgeo** [comment]
Hi @SPlanzer, please update with expected effort for DWG today (3pm), or close if fixed.

**Comment by SPlanzer** [comment]
API patch has resolved this  - @Deb-Jones to test

**Comment by Deb-Jones** [comment]
Looks wrong until refresh comes through. Then displays correctly. Will mark as passed, but will reopen if it causes confusion to other users.
