### ISSUE TITLE
Create New Address Form - Comments - Not passed to API

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#17]
When the Comments field is populated the value is not passed to the API.

**Comment by SPlanzer** [comment]
Implemented - please test in next version

**Comment by Deb-Jones** [comment]
Retested and comments still not passing to API.

**Comment by Deb-Jones** [comment]
Rechecked, was looking at the wrong field. Notes are passing to sourceReason.
