### ISSUE TITLE
Review Queue - Display of Warnings

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#170]
Warnings are not showing up on the review queue until you close out of QGIS and go back in.

**Comment by billgeo** [comment]
Hi @SPlanzer , please update with expected effort for DWG today (3pm), or close if fixed.

**Comment by SPlanzer** [comment]
With API patch this has been solved - @Deb-Jones  to test

**Comment by Deb-Jones** [comment]
Tested. Passed.
