### ISSUE TITLE
After new road creation use of Road center line selector checked and adding new address

### ISSUE THREAD

**Issue by LinzDSie** [linz/QGIS-AIMS-Plugin#179]
After adding a new road, the road center line selector tool check box is checked, if a new address is added returns the following error:

An error has occurred while executing Python code:

Traceback (most recent call last):
  File "D:\Users\DSie.qgis2\python\plugins\aims\AimsUI\CreateNewAddressTool.py", line 107, in canvasReleaseEvent
    self.NewAimsFeature(coords)
  File "D:\Users\DSie.qgis2\python\plugins\aims\AimsUI\CreateNewAddressTool.py", line 144, in NewAimsFeature
    self._controller._queues.uEditFeatureTab.setFeature('add', addInstance, coords)
  File "D:/Users/DSie/.qgis2/python/plugins\aims\AimsUI\AimsClient\Gui\EditFeatureWidget.py", line 107, in setFeature
    self._controller._rcltool.fillform()
  File "D:\Users\DSie.qgis2\python\plugins\aims\AimsUI\GetRclTool.py", line 112, in fillform
    self.highlight.setRcl(self.rclLine)
  File "D:\Users\DSie.qgis2\python\plugins\aims\AimsUI\AimsClient\Gui\FeatureHighlighter.py", line 157, in setRcl
    self._rclMarker.setToGeometry(QgsGeometry.fromPolyline(line[0]),None)#,rclLayer)
TypeError: 'NoneType' object has no attribute '__getitem__'

Python version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

QGIS version:
2.8.7-Wien Wien, 8a47921

Python path: ['G:/QGISWI~1/apps/qgis-ltr/./python/plugins\processing', 'D:\Users\DSie\.qgis2\python\plugins\aims', 'G:/QGISWI~1/apps/qgis-ltr/./python', u'D:/Users/DSie/.qgis2/python', u'D:/Users/DSie/.qgis2/python/plugins', 'G:/QGISWI~1/apps/qgis-ltr/./python/plugins', 'C:\Program Files (x86)\ArcGIS\bin', 'G:\QGISWI~1\bin\python27.zip', 'G:\QGISWI~1\apps\Python27\DLLs', 'G:\QGISWI~1\apps\Python27\lib', 'G:\QGISWI~1\apps\Python27\lib\plat-win', 'G:\QGISWI~1\apps\Python27\lib\lib-tk', 'G:\QGISWI~1\bin', 'G:\QGISWI~1\apps\Python27', 'G:\QGISWI~1\apps\Python27\lib\site-packages', 'G:\QGISWI~1\apps\Python27\lib\site-packages\PIL', 'G:\QGISWI~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg', 'G:\QGISWI~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win32.egg', 'G:\QGISWI~1\apps\Python27\lib\site-packages\python_dateutil-2.2-py2.7.egg', 'G:\QGISWI~1\apps\Python27\lib\site-packages\pytz-2014.2-py2.7.egg', 'G:\QGISWI~1\apps\Python27\lib\site-packages\win32', 'G:\QGISWI~1\apps\Python27\lib\site-packages\win32\lib', 'G:\QGISWI~1\apps\Python27\lib\site-packages\Pythonwin', 'G:\QGISWI~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win32.egg', 'G:\QGISWI~1\apps\Python27\lib\site-packages\six-1.10.0-py2.7.egg', 'G:\QGISWI~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', u'D:/Users/DSie/.qgis2//python', '..', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', 'G:\QGISWI~1\apps\qgis-ltr\python\plugins\fTools\tools', 'G:\QGISWI~1\apps\qgis-ltr\python\plugins\intramaps_qgis\ui', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc']

**Comment by SPlanzer** [comment]
@LinzDSie Please retest in next release of plugin (v > 0.8.22)
