### ISSUE TITLE
Create New Address From - Meshblock Override

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#18]
Meshblock is not being displayed and Meshblock Override is not on the form.
This is because it was not included in the 1A build of the API.
e-Spatial are developing it so it should be included in a later sprint once it's been implemented in the API.

**Comment by Deb-Jones** [comment]
We need Meshblock Override on the Feature form because there are around 80 addresses that fall outside all meshblocks and therefore require an override to be entered.

**Comment by SPlanzer** [comment]
Please retest in 0.8.2

**Comment by Deb-Jones** [comment]
Tested 0.8.2

Meshblock override saved and displayed against the published address.

Have raised a separate query to find out where this is stored in the database.

**Comment by Deb-Jones** [comment]
Every time you edit an address, the meshblock override is populated with the current meshblock.

**Comment by Deb-Jones** [comment]
The issue is that the edit feature form reads stage.address_publish.meshblock. This database field includes the meshblock (point in polygon) or the meshblock override. Nothing in the table advises whether this field includes the point in polygon meshblock or the meshblock override.

If this field on the add feature or edit feature of the UI is populated, the stage.address_meshblock_override will be populated and the stage.address_publish.meshblock will be populated with the meshblock override.

If this field is not populated on the add feature or edit feature of the UI, the stage.address_publish.meshblock will be populated with the point in polygon meshblock.

So, when the user edits an address, Meshblock Override on the UI is populated with the stage.address_publish.meshblock. If you leave it there, the address suddenly has a meshblock override. If you delete it, any valid meshblock override will be deleted from the published address.

You don't want the meshblock override being populated with the point in polygon meshblock because when a reference data update edits the meshblock, it won't update the published meshblock for that record because it has an override.

I suspect it's an API edit that's required to fix this but I don't know for sure.

**Comment by Deb-Jones** [comment]
Assigned to @rgabara because we need to discuss where to go from here.

**Comment by Deb-Jones** [comment]
e-Spatial to edit the API to include an isMeshblockOverride flag.
This edit will be included in today's API release.

UI to be adapted so that during an edit and on the review queue, the Meshblock Override field is only automatically populated when isMeshblockOverride flag is set to T.

No change required to add.

**Comment by Deb-Jones** [comment]
The additional field was added to the database, but not the API. It should be included in tomorrow's API release.

After that, UI can be adapted.

**Comment by billgeo** [comment]
As discussed can get this out for v1.0 release on Monday evening.

**Comment by SPlanzer** [comment]
Please Retest in 8.10

**Comment by Deb-Jones** [comment]
Tested 0.8.10. PASS.
