### ISSUE TITLE
Source Notes carried on to address move

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#185]
If the previous address change had source notes, a move will keep the previous source notes.

This may not be a new issue. I haven't directly tested for it. I noticed it when moving an address that I had previously done a roads reference data edit on.

Could cause confusion if the comment refers to a previous change. Not a show stopper for go live.

**Comment by SPlanzer** [comment]
Please retest in next release.

Note; the config files requires an extra line
"MERGE_EXCLUDE = 'workflow_sourceReason'"

This has been added to the config template

**Comment by Deb-Jones** [comment]
The source notes do not persist if the features have refreshed.

**Comment by ghost** [comment]
This is caused by the ConfigParser library which rewrites the entire config file from stored values every time it is saved. Comments don't get loaded when the keys/values are read so are lost when these values are resaved.
