### ISSUE TITLE
Python Error When Declining a Modify

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#186]
If I edit an address (either move or modify) and then decline the change, I get the following python error.

The actual change does get declined.
select cq.changeid, ct.addresschangetypename, qs.addressqueuestatus
from aims_stage.change_queue cq
join aims_systemconfig.address_change_type ct
on cq.changetypeid = ct.addresschangetypeid
join aims_systemconfig.address_queue_status qs
on cq.queuestatusid = qs.addressqueuestatusid
where cq.changeid = 1919487
![image](https://cloud.githubusercontent.com/assets/15723101/18495982/10d1570c-7a76-11e6-940a-2e5c5a119b42.png)

An error has occurred while executing Python code:

Traceback (most recent call last):
  File "D:/Users/djjones/.qgis2/python/plugins\aims\AimsUI\AimsClient\Gui\ReviewQueueWidget.py", line 426, in decline
    self.reviewResolution('decline')
  File "D:/Users/djjones/.qgis2/python/plugins\aims\AimsUI\AimsClient\Gui\ReviewQueueWidget.py", line 417, in reviewResolution
    if self._controller.RespHandler.handleResp(respId, feedType, action):
  File "D:\Users\djjones.qgis2\python\plugins\aims\AimsUI\AimsClient\Gui\ResponseHandler.py", line 163, in handleResp
    if self.matchResp(resp, respId, feedType, i, action):
  File "D:\Users\djjones.qgis2\python\plugins\aims\AimsUI\AimsClient\Gui\ResponseHandler.py", line 144, in matchResp
    self.updateData(resp, feedType, action)
  File "D:\Users\djjones.qgis2\python\plugins\aims\AimsUI\AimsClient\Gui\ResponseHandler.py", line 57, in updateData
    self.uidm.updateGdata(respObj)
  File "D:\Users\djjones.qgis2\python\plugins\aims\AimsUI\AimsClient\Gui\UiDataManager.py", line 233, in updateGdata
    self.data[FEEDS['GR']][groupKey][respFeature._changeId] = respFeature
KeyError: None

Python version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

QGIS version:
2.8.7-Wien Wien, 8a47921

Python path: ['D:/Users/djjones/.qgis2/python/plugins\processing', 'D:\Users\djjones\.qgis2\python\plugins\aims', 'G:/QGIS28/apps/qgis-ltr/./python', u'D:/Users/djjones/.qgis2/python', u'D:/Users/djjones/.qgis2/python/plugins', 'G:/QGIS28/apps/qgis-ltr/./python/plugins', 'C:\Program Files (x86)\ArcGIS\bin', 'G:\QGIS28\bin\python27.zip', 'G:\QGIS28\apps\Python27\DLLs', 'G:\QGIS28\apps\Python27\lib', 'G:\QGIS28\apps\Python27\lib\plat-win', 'G:\QGIS28\apps\Python27\lib\lib-tk', 'G:\QGIS28\bin', 'G:\QGIS28\apps\Python27', 'G:\QGIS28\apps\Python27\lib\site-packages', 'G:\QGIS28\apps\Python27\lib\site-packages\PIL', 'G:\QGIS28\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win32.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\python_dateutil-2.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\pytz-2014.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\win32', 'G:\QGIS28\apps\Python27\lib\site-packages\win32\lib', 'G:\QGIS28\apps\Python27\lib\site-packages\Pythonwin', 'G:\QGIS28\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win32.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\six-1.10.0-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', u'D:/Users/djjones/.qgis2//python', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '..', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', 'D:\Users\djjones\.qgis2\python\plugins\intramaps_qgis\ui', 'G:\QGIS28\apps\qgis-ltr\python\plugins\ElectoralAddressPlugin', 'G:\QGIS28\apps\qgis-ltr\python\plugins\fTools\tools', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc']

**Comment by SPlanzer** [comment]
@Deb-Jones at what frequency do you see this occur? every time you perform an update?

**Comment by Deb-Jones** [comment]
It's not occurring today.

I suspect it is a time out type thing. The declines were happening. We should make this a low priority.

**Comment by SPlanzer** [comment]
I cant reproduce it but looking at the trace back I can add some extra handling to ensure non responses do not cause such errors
