### ISSUE TITLE
Road Labels disappear

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#187]
Road labels disappear from the edit feature tab after I've switched between address type road to water and back again.

![image](https://cloud.githubusercontent.com/assets/15723101/18497829/d6730f96-7a85-11e6-9c06-ba027d4a590c.png)

**Comment by Deb-Jones** [comment]
They're also gone from the review tab.

![image](https://cloud.githubusercontent.com/assets/15723101/18497840/f219a23c-7a85-11e6-8df7-53d4e322f313.png)

**Comment by SPlanzer** [comment]
Please retest

**Comment by SPlanzer** [comment]
@Deb this should have been rolled out in version 1.0.0. Can you confirm and remove the test label

**Comment by Deb-Jones** [comment]
Tested. Acceptable.
