### ISSUE TITLE
Review Panel too narrow

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#188]
The review panel width has been reduced and you have to scroll to see the drop down arrows and rcl select button.

Can it be widened again please?

![image](https://cloud.githubusercontent.com/assets/15723101/18499405/b21ea60c-7a92-11e6-8783-afb9cce137ca.png)

**Comment by SPlanzer** [comment]
@Deb-Jones please review in the next version

**Comment by SPlanzer** [comment]
@Deb this should have been rolled out in version 1.0.0. Can you confirm and remove the test label

**Comment by Deb-Jones** [comment]
Version 1.0.0 in QGIS 2.8.7 this is fine.
Version 1.0.0 in QGIS 2.14.8 it is narrow again.

@SPlanzer how hard is it to change this for the default view? We don't want to have to change it every time we open the AIMS Plugin. I suggest we make the new version the correct width for 2.14.8.

**Comment by Deb-Jones** [comment]
Currently displays correctly.
