### ISSUE TITLE
Create New Address Form - Road Centreline ID - make non-editable

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#19]
Phase 1A defined that the system requires an addressNumber and roadName to be supplied for an address.  If a roadCentrelineId is also supplied then AIMS will check that the roadName supplied matches that on the road centreline.  There can be no guarantee that a roadCentrelineId passed to the AIMS API is from the LINZ road dataset or is a valid value, therefore AIMS does not accept only a roadCentrelineId.

The impact of this is that a user should not be able to type in a Road Centreline ID.

**Comment by SPlanzer** [comment]
Implemented - please test in next version

**Comment by Deb-Jones** [comment]
Retested. Road Centreline ID not editable in the UI.
