### ISSUE TITLE
Map - Road Parcels

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#194]
Make road parcels more identifiable on the map. For example, in Landonline the road parcels have an orange fill.

**Comment by billgeo** [comment]
@SPlanzer - should be a simple change I take it. Let's plan to do this in the first patch release.

**Comment by billgeo** [comment]
@SPlanzer - can you release this one with #200

**Comment by SPlanzer** [comment]
easy -  @Deb-Jones, pay me a visit prior to the next release and we can get it right to your liking. This will only take a minute

**Comment by SPlanzer** [comment]
Actually, @Deb-Jones , Get the roads styled how you like them and save a QGIS Layer Style File. 

That is:
* Edit the Road layer style via the Layer Properties menu.
* Once the layer is looking good:
  * Select "Style" at the bottom of the layer properties dialog > "Save Style" > "QGIS Layer Style File..."

We can then push this outputted file to GitHub and roll it out for the next release.

**Comment by SPlanzer** [comment]
Done, will be rolled out as part of next release. Thanks @Deb-Jones
