### ISSUE TITLE
Bulk Load of Address Ranges

### ISSUE THREAD

**Issue by linzbjones** [linz/QGIS-AIMS-Plugin#204]
@imincik Can we please use some of @SPlanzer time to push through a bulk load of addresses to AIMS?

Can you please give me a time frame on when he would be available to do this work?

**Comment by imincik** [comment]
@linzbjones , I am OK if @SPlanzer will do it this week ( @SPlanzer , please move this task to our project management if you will decide to work on it ) .

**Comment by SPlanzer** [comment]
Hi @linzbjones. Feel free to send someone my way provide the details of this task.

**Comment by SPlanzer** [comment]
closing. The be managed as part of data service issue [#140](https://github.com/linz/LI-tasks/issues/140)
