### ISSUE TITLE
User able to add address with addressable object type Building

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#206]
If a user adds an address with an addressable object type of building a box pops up with the error "Action Rejected AddressableObjectID cant be assigned using the spatial Address object". This is correct behaviour.

If a user adds an address with an addressable object type of parcel and submits. The user then modifies the addressable object type to building within the queue. The system allows the user to accept the address without any error. This is not correct behaviour.

The impact is that an address record is created with an addressable object type of building, using the addressableobjectid of the parcel it was originally associated with.

This was detected by a customer (Infolog) because in the LDS extract the address_reference table has null values in the address_reference_object_value .

**Comment by SPlanzer** [comment]
Hi @Deb-Jones 

This sounds like one for the API as opposed to the plugin. The UI relies on the API's behaviour concerning warnings / rejections. This must therefore be solve at the API level to halt any further data corruption.

**Comment by Deb-Jones** [comment]
Replaced by issue https://github.com/linz/AIMS/issues/267
