### ISSUE TITLE
Enhancement: Ability to upload .csv onto change queue

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#207]
As a user of AIMS I want the ability to simply add multiple items to the change queue from a correctly formatted .csv.

It is probable that this code can be built on to provide bulk loads.
Users will need to add or modify addresses.
For modify, any parameter of the address could be modified (e.g. position type).
The developer will need to advise the required format of the .csv.

The purpose of this enhancement is to facilitate data quality improvement work.

**Comment by imincik** [comment]
@SPlanzer ,  this is good to be done until mid-July.

**Comment by Deb-Jones** [comment]
Can I please have an update on when this is expected to be delivered?

**Comment by SPlanzer** [comment]
Sorry hadn't seen this one. 

I would really need to sit with @Deb-Jones to scope this one out to get any time frames together. Though it is almost mid-july now. I will raise this at next weeks planning session  - it will be up to @imincik to prioritise.

**Comment by imincik** [comment]
@Deb-Jones , it is not possible to do it this week for sure. It will be great, if we will have discussion next week.

**Comment by imincik** [comment]
@Deb-Jones , the best we can do this week is to have 30 minutes meeting to better understand and document your needs. @SPlanzer will organize the meeting.

**Comment by SPlanzer** [comment]
Hi @Deb-Jones. As above lets organise 30min this week to scope this piece of work. I am on leave Thur/Fri but anytime tomorrow or Wednesday afternoon suits me

**Comment by Deb-Jones** [comment]
Merged into https://github.com/linz/QGIS-AIMS-Plugin/issues/209
