### ISSUE TITLE
Opening the AIMS plugin crashes QGIS

### ISSUE THREAD

**Issue by jason-bedford** [linz/QGIS-AIMS-Plugin#218]
If I try and open the AIMS plugin on my laptop it crashes QGIS (2.8.7).
I tried re-installing the plugin but it made no difference.
It started doing this a couple of weeks ago, and had been working fine before then.
I am able to use it OK when in DaaS.

**Comment by SPlanzer** [comment]
I didn't change anything. If it wasn't me that broke it, I assume you broke it.

**Comment by SPlanzer** [comment]
But seriously, 2.8 is on the way out. I am going to create a new release for 2.18 this week. We will test the plugin against both daas and desktop environments and remedy then if required.

**Comment by SPlanzer** [comment]
Im going to close this and we will open a new issue for the 2.18 plugin release
