### ISSUE TITLE
Add Nina to AIMS

### ISSUE THREAD

**Issue by SPlanzer** [linz/QGIS-AIMS-Plugin#233]
from @YingtingChen 
> please add Nina Barcinska (NBarcinska) to prdassgeo01 user list (same roles as the addressing team member). 

Adding here to track task and follow up questions

**Comment by SPlanzer** [comment]
Hi @YingtingChen 

I have added this task here to track as it has multiple steps. 

Does she also also require access to the AIMS API?

**Comment by YingtingChen** [comment]
If she will use the AIMS plugin then yes she needs access to api as well.
We have [page](https://confluence.linz.govt.nz/display/GEOD/AIMS+Plugin+Setup) that lists all the things that need to be done. And I believe I can set up the tomcat user from my end :)

**Comment by SPlanzer** [comment]
Ah. great. I'll do the database side before I go home tonight. 
Let me know if you need a hand with the API user or Tomcat side

**Comment by YingtingChen** [comment]
Sweet. Thanks for the help!

**Comment by SPlanzer** [comment]
new user created on prd

```
-- Role: NBarcinska

-- DROP ROLE "NBarcinska";

CREATE ROLE "NBarcinska" LOGIN
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT bde_user TO "NBarcinska";
GRANT roads_user TO "NBarcinska";
COMMENT ON ROLE "NBarcinska" IS 'LINZ Addressing user';

```
