### ISSUE TITLE
Map - Identify stacked address

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#27]
Stacked addresses can be seen on the map, but only because there are multiple address numbers and one point. From a functional perspective this is adequate, but would be more user friendly if it was easier to identify stacked addresses by looking at the map.

![image](https://cloud.githubusercontent.com/assets/15723101/11460557/5f6f25e4-9753-11e5-8ed8-d7f318bb0077.png)

**Comment by billgeo** [comment]
Also one for Ian Reese?

**Comment by SPlanzer** [comment]
@billgeo - If he likes, However I suspect the solution would require a fair bit of coding to summarise the addresses within the stacks

**Comment by Deb-Jones** [comment]
It might be something that we wait until we've implemented primary/sub addressing so we can utilise the primary address as a label.

**Comment by Deb-Jones** [comment]
It is no longer possible to see stacked addresses on the map.

![image](https://cloud.githubusercontent.com/assets/15723101/17081204/0ec879d2-51a3-11e6-8cc7-ea6a346116c5.png)

The example in the image above is 6 addresses stacked on top of each other. 20A to 20F.

**Comment by SPlanzer** [comment]
Fixed Please re test
