### ISSUE TITLE
Retire Address - retire stacked address

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#29]
When a single address is retired, a confirmation pop-up is displayed giving the user a chance to cancel the retirement. No pop-up appears for a stacked address.

![image](https://cloud.githubusercontent.com/assets/15723101/11460622/9ea0c460-9754-11e5-8598-c00cbae0b2ad.png)

**Comment by SPlanzer** [comment]
The reason the above message box was added is to make the retirement action explicit. i.e. as opposed to the user just clicking on an point and the address being retired.

With stacked addresses the user selects the stack and the below dialogue appears. The user then selects from the stack which addresses should be retired. The user then has the chance to select "ok" or "cancel". this is the point at with an stacked address retirement can be aborted.  

I feel any more dialogues such as "are you sure you really want to delete addresses x,y,z? " would be overkill and an unnecessary step as the user already has the opportunity to review there addresses selected for retirement and then abort the action

I have closed this issue but feel free to reopen and add to the case for extra opportunity to abort retirement. 

![screenshot from 2015-11-30 13 00 53](https://cloud.githubusercontent.com/assets/10425696/11461165/7be25d2c-9762-11e5-8c45-80b2a4cf2cb0.png)
