### ISSUE TITLE
MAP - Address Labels

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#36]
Address labels are not clear when aerial imagery is used. Can the default please be changed to add a white buffer to the address labels?
This is a nice-to-have, not essential.

**Comment by billgeo** [comment]
Simon, this is something Ian Reese could look at potentially.

**Comment by SPlanzer** [comment]
@billgeo, Seems deb just wants a white buffer around labels. This is a two min job for me. It would take Ian much longer to check out the source code, and update the .qml files.

**Comment by Deb-Jones** [comment]
Tested 0.8.16. Passed.
