### ISSUE TITLE
Concerns concerning timing of responses after a new bounding box is set. 

### ISSUE THREAD

**Issue by SPlanzer** [linz/QGIS-AIMS-Plugin#39]

**Comment by SPlanzer** [comment]
It has been decided that solutions must be tabled and not action taken until approval for a solution granted

**Comment by SPlanzer** [comment]
In the mean time I will gather metrics as to quantify the issue

**Comment by josephramsay** [comment]
Responsiveness Improvement Suggestions
1. Pre-cache address points from disk and display in map window only populating status data during update cycle and/or bbox request (significant rewrite of dm code section, appearance of responsiveness, depends on QThreads in UI to be effective)
2. Spawn multiple bbox fetch threads without waiting for previous threads to die (risk of api overload/slowdown and data contention issues)
3. Abandon periodic updates in map window/features thread. (Will only improve responsiveness in cases where periodic update would normally be interrupted)

**Comment by david1jewell** [comment]
Address feature data could be refreshed from API via something similar to the old address-publish feed (developped then dropped in 1A), which retreived only changes to a bbox since it was last run. It may also be possible to achieve this for change & resolution feeds.

**Comment by david1jewell** [comment]
Another option to speedup responses from the API from the features list would be to only bring back relevant field to show on the map/list. At present most of the time spent is on extracting all the fields, so reducting to just a few (eg addressid, fulladdressnumber, fulladdress, primary position) often takes less than 20% the time to retreive the full details. There could be a parameter to control this. This would mean the selecting an address to show/edit would then need to query to get the full details, but only for the 1 selected.

**Comment by Deb-Jones** [comment]
@rgabara to follow up with @josephramsay

**Comment by josephramsay** [comment]
_4. Delay bbox requests till user has finished panning map window. Detect user-interaction state or provide a button to explicitly refresh map window. (Introduces additional delays)
_5. Zoom layer map window to only show points < 1000 so only one page is requested at a time (Window size not a good indicator of point density)

**Comment by josephramsay** [comment]
Lowering the THREAD_JOIN_TIMEOUT improves this issue though may effect stability. Have added additional breaks to prevent stopped threads progressing
