### ISSUE TITLE
Edit Feature form - Unit Type field label missing

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#41]
The Unit Type label is not displaying on the Edit Feature form.

**Comment by Deb-Jones** [comment]
Assigned version 1.1 because it's the only field missing a label, and there is a drop down associated which makes it clear what the field is. Not worth spending time on pre-go-live.

**Comment by SPlanzer** [comment]
Please Retest in 0.8.2

**Comment by Deb-Jones** [comment]
0.8.2 Tested

Label is there.
