### ISSUE TITLE
Validation Rule - Address is not Unique on the road object

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#42]
Every time I create a new address populating only base address and road name, the resolution feed link and the change feed link advise that the address is not unique on the road object. This is when the address is unique.
http://144.66.241.207:8080/aims/api/address/resolutionfeed/4881218
http://144.66.241.207:8080/aims/api/address/changefeed/4881218
The warning does not appear on the Review queue in the UI.
I am not able to accept the Add. A warning pops up saying Address is not unique on the road object.
The warning is not created if there is an alpha.

If I create a duplicate that really is a duplicate with an alpha two warnings are generated; Address is not unique on the road object and Address is not unique within the suburb. - This is correct functionality.

If I create a duplicate that really is a duplicate with no alpha two warnings are generated; Address is not unique on the road object and Address is not unique within the suburb. - This is correct functionality.

**Comment by Lisa-Merwood** [comment]
@shane-turk-espatial could you please take a look at this bug from Deb.

**Comment by Deb-Jones** [comment]
There is an update to this. It is not happening everywhere.
Addresses where it has occurred include;
3, 10, 13 Pamela Place, Otumoetai, Tauranga
15, 17, 24 Hillcrest Road, Otumoetai, Tauranga
10 Stratford Place, Otumoetai, Tauranga
It did not occur for;
123 Grange Road, Otumoetai Tauranga
5 Lees Way, Otumoetai, Tauranga
10 Apollo Street, Otumoetai, Tauranga
These three addresses are between the addresses where it is happening. So it's not unique to the locality or meshblock.
I haven't seen it outside of the examples above either, but it does occur every time I create an address on those roads.

**Comment by Deb-Jones** [comment]
I am also getting this error on The Esplanade, Petone, Lower Hutt. 7, 19 and 31.

**Comment by shane-turk-espatial** [comment]
I have produced the validation warning for each of the examples that you have raised.  I am now investigating.  If there is an updated database function required how do you want this supplied?

**Comment by shane-turk-espatial** [comment]
@Deb-Jones @SPlanzer

**Comment by shane-turk-espatial** [comment]
The fnProcessAddress has been altered to include a check for suburb.  Once introduced 13 Pamela Place is not returned as a duplicate.  The tests were performed for Hillcrest Road, and Stratford Place without any issues. In the screenshot (attached), number 3 and 10 already look as though they are proper address and should return duplicates. An update validation function has also been attached.  I understand that this is not as per the current process but it should allow quicker retesting.

![screenshot_42](https://cloud.githubusercontent.com/assets/13779587/14947269/a00c050e-1084-11e6-8be7-96825620e1c3.png)

**Comment by Deb-Jones** [comment]
Wasn't sure who to assign this to, but I need Shane's bug fix implemented to enable me to test it again.

**Comment by shane-turk-espatial** [comment]
ready for retest once script has been deployed.

**Comment by Deb-Jones** [comment]
Retested. Error no longer occurring.
