### ISSUE TITLE
Review Queue - Display of Warnings

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#43]
When you add an address and a warning is created, the change appears on the review queue but the warning is not displayed.

When you close QGIS and re-open it the warning displays.

Even when the warning is not displayed, the user is unable to accept a change with a warning.

**Comment by SPlanzer** [comment]
Please retest in 0.8.1

**Comment by Deb-Jones** [comment]
Tested 0.8.1
Warnings are appearing on the review queue immediately.
