### ISSUE TITLE
Feature Form - Select Road Segment Tool

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#45]
When there are multiple road segments on top of each other, or very close to each other, the select road segment tool is unable to find a segment.

After activating the tool, it is not possible to submit an add without entering the road centreline id. The Road Centreline Id field is not editable, so you can't enter it manually.

Examples;
Maungawhare Place, Otumoetai, Tauranga. RCL_ID 324907 (two instances), 140366
Otumoetai Road, Otumoetai, Tauranga. RCL_ID 324909, 133585

I don't think we should have more than one RCL_ID. In Landonline there is only one segment for each of these road sections, and only one name. The problem could be historic data or test data in the roads tables.

**Comment by dwsilk** [comment]
I've removed historic data from the view that the QGIS-AIMS-Plugin was using.
