### ISSUE TITLE
Feature Form - punctuation

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#46]
Users should not be able to enter punctuation in the following fields;
Base
High

Users can enter + or - in these fields and submit the address. The punctuation disappears before it hits the change feed. If + or - is entered in Base, an error pops up saying that AddressNumber must be provided.

Unit should also not allow punctuation but does allow _
The _ is passed through to the change feed and can be accepted.

**Comment by Deb-Jones** [comment]
Also, all the road name component fields allow any punctuation but they should not allow any punctuation other than the road name field which should only allow dash, apostrophe and space.

**Comment by Deb-Jones** [comment]
Assigned version 1.1 because the only real risk to the database is that a user can add _ as a unit number. Users can avoid doing that.

**Comment by Deb-Jones** [comment]
You are able to enter punctuation in the QA Update form. When you accept, this is then published in the address publish table.

select changeid, unitvalue, levelvalue, addressnumbersuffix, fulladdressnumber
from aims_stage.change_address
where changeid = 2805089

2805089;"#$";"!@-";"%^";"#$/24%^"

select changeid, unitvalue, levelvalue, addressnumbersuffix, fulladdressnumber
from aims_stage.address_publish
where changeid = 2805089
2805089;"#$";"!@-";"%^";"#$/24%^"

I was prevented entering - in unit and suffix fields.

Reassigned to 0.8.13 because random punctuation can end up in the address publish table by entering it through the QA update.

**Comment by SPlanzer** [comment]
unit value, level value, num prefix,  base num, num suffix and num high now all have restricted input (\w)

Please test and advise of any other fields that may require further masking.

**Comment by Deb-Jones** [comment]
Tested 0.8.16. Not fixed.

Base - allows - +
High - allows - +
Unit Value - allows _
Level Value - allows _
Address Prefix - allows _
Alpha - pass

**Comment by SPlanzer** [comment]
Interesting, 

Base and High were being passed through a QIntValidator. Now QRegExp(r'[0-9])

Unit, Level and Address Prefix were limited to \w. Now  QRegExp(r'[0-9A-Za-z]')

**Comment by Deb-Jones** [comment]
Tested 0.8.17. Passed.
