### ISSUE TITLE
Feature Form - Road Name Components

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#48]
It is a requirement to type in the required road name components, or an alias of the required road name and for the associated Road Centreline to be populated from the system.

When you enter road name components, and a base address, and then submit, an error pops up "No Road Centreline Supplied". You are not able to submit the address.

**Comment by Deb-Jones** [comment]
Classified as version 1.1 because the process will be that the user can click on the road centreline. This function will need addressing as part of 1.1 to consume spatial files.

**Comment by SPlanzer** [comment]
Please Retest in 0.8.1

The UI will now proceed to submit the information to the API if the minimum required 'Feature Form' fields are populate. The minimum required fields that must be populated in the UI are; base number and road name.

**Comment by Deb-Jones** [comment]
Tested 0.8.1
Able to enter number and road name.
