### ISSUE TITLE
Feature Form - case

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#49]
When lower case alphas are entered into the unit or alpha field they should be upper cased when sent to the API. The database should not hold any lower cased alphas in unit or alpha field.

When you enter lower case in unit or alpha, the message to the API is lower case. When you accept the address, the published data shows as lower case.

**Comment by Deb-Jones** [comment]
prefix should also be upper cased, but it is being published as lower case.

**Comment by Deb-Jones** [comment]
@rgabara yesterday we discussed this being done in the database. Should this issue be reassigned to e-Spatial?

**Comment by Deb-Jones** [comment]
A separate issue has been raised in the AIMS repository for this to be implemented in the API or Database, Issue 66. This issue remains open to implement upper casing in the UI. The following fields are affected:
Unit Value
Level Value
Address Number Prefix
Address Number Suffix

**Comment by SPlanzer** [comment]
please retest in 0.8.1

**Comment by Deb-Jones** [comment]
Tested 0.8.1
All four fields entered lower case, submitted as upper case.
