### ISSUE TITLE
Map - Missing Proposed Addresses

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#50]
When an address is created with a life cycle of Proposed, it does not display on the map.

Examples;
Address ID 1787856 - "3 Nevis Street, Petone, Lower Hutt"
Address ID 1787851 - "Apartment 10a, ran113b The Esplanade, Petone, Lower Hutt"

**Comment by Deb-Jones** [comment]
Not a go live priority because there is currently no business process for TAs to advise us that an address is proposed, or that an address has changed from proposed to current.

**Comment by SPlanzer** [comment]
Add to the aims Feature Layer

Please test in 0.8.1

**Comment by Deb-Jones** [comment]
Tested 0.8.1
Proposed addresses display as orange.
