### ISSUE TITLE
Feature Form - Comments

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#51]
The comments entered in Notes do not clear when you submit a change. So the next change you create has the same notes as you previously entered.

This should clear upon submit.

**Comment by Deb-Jones** [comment]
Workaround would be to manually clear this out.

**Comment by SPlanzer** [comment]
Please retest in 0.8.1

**Comment by Deb-Jones** [comment]
Tested 0.8.1
Comments cleared out.
