### ISSUE TITLE
Submit Address - High

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#52]
When I create an address with base and high (i.e. a ranged address), the layer in the UI and the Review Queue has a ranged address. But when I accept the address, the high number disappears and the address only has the base number.

Examples; Address ID 1787859 - 102-104 Upper Puniho Road
Address ID 1787858 - 12345-12347 Upper Puniho Road

**Comment by Deb-Jones** [comment]
Additionally, Validation rule 28, AddressNumberHigh cant be supplied for an Insert, rule ID AIMS: V0012, Severity Info, Visible = True. The review queue should get an info about this, but no info is being displayed. No info appears on the messages.
http://144.66.241.207:8080/aims/api/address/changefeed/4881269
http://144.66.241.207:8080/aims/api/address/resolutionfeed/4881269

**Comment by shane-turk-espatial** [comment]
We have investigated the API and the database functions fnProcessAddress and fnPublishAddress and all three components allow an address with an address high range to be inserted.  The validation fnPublishAddress will raise an INFO for the message "AddressNumberHigh cant be supplied for an Insert";"AIMS: V0012".  I processed the address example for 102-104 Upper Puniho Road and it was accepted with the single info message raised above.

**Comment by Deb-Jones** [comment]
[GitHub Issue 52.docx](https://github.com/linz/QGIS-AIMS-Plugin/files/248024/GitHub.Issue.52.docx)

The High field isn't getting passed through to the API. I've attached all my steps for an example.

**Comment by SPlanzer** [comment]
Please retest in 0.8.1

**Comment by Deb-Jones** [comment]
Tested 0.8.1
Address high now being submitted and recorded in database once add is approved.
