### ISSUE TITLE
Review Queue - Display of Infos

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#53]
Infos are not appearing on the Review Queue. Even if I close QGIS and reopen it, the infos are not displaying.

Example, Change ID 4881270
 "ruleId":"AIMS: V0012",
                "description":"Address Number or Address Number High Could be Too Large",
                "severity":"Info"

There is no info on the review queue for this change.

**Comment by SPlanzer** [comment]
Please retest in 0.8.1

**Comment by Deb-Jones** [comment]
Tested 0.8.1
Infos now display.
