### ISSUE TITLE
Roads - Chatham Islands

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#54]
When you navigate to the Chatham Islands the roads appear in a different location to the AIMS features (addresses).

**Comment by billgeo** [comment]
All Chathams data should appear west of NZ (0-360 coordinates). This will be fixed in https://github.com/linz/QGIS-Roads-Plugin/issues/27

Can be closed here.

**Comment by Deb-Jones** [comment]
Retest when next release goes in.

**Comment by Deb-Jones** [comment]
Tested 0.8.9.
roads and address points are in the same place. Parcels are not.

Will this be fixed with the 7/6 release into test?

**Comment by billgeo** [comment]
To clarify, parcels are in the 'right place' and roads and address points need to have 0-360 coordinates. 

@dwsilk can you answer this for Deb from the roads point of view? I can confirm that this _should_ be the case for the address points when e-Spatial deliver their migration scripts in the next release.

**Comment by dwsilk** [comment]
Roads are in the right place in test. I haven't updated dev data as it would then be out of sync with the address data. Back to Deb to retest after e-Spatial's next migration.

**Comment by Deb-Jones** [comment]
Tested 22/6/16.
Roads are in the same place as address points and parcels.
