### ISSUE TITLE
Reference Data - Chatham Islands

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#55]
I have not found the Chatham Islands reference data. It is not near the roads, and it is not near the address points.

**Comment by billgeo** [comment]
All Chathams data should appear west of NZ (0-360 coordinates). This will be fixed in https://github.com/linz/AIMS/issues/1.

Can be closed here once retested.

**Comment by Deb-Jones** [comment]
Roads, address points, parcels, meshblocks, localities all in the same place.

towncity is not being populated.

**Comment by billgeo** [comment]
@shane-turk-espatial is this a bug? Or is there no town/city data in the chathams?

**Comment by shane-turk-espatial** [comment]
checking the data

**Comment by shane-turk-espatial** [comment]
There is only suburb_4th data populated for chatham island.  The data has been correctly populated with only chatham island.

select \* from aims_stage.address_publish
where suburblocalityid = 8673

**Comment by billgeo** [comment]
So what Deb is seeing is expected behaviour? Will this cause any problems elsewhere in the system?

**Comment by billgeo** [comment]
Closing this issue
