### ISSUE TITLE
Get Road Centreline Tool - Macrons

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#57]
Unable to select a road centreline that contains a macron. A Python Error is generated.

Traceback (most recent call last):
  File "D:\Users\djjones.qgis2\python\plugins\aims\AimsUI\GetRclTool.py", line 92, in canvasReleaseEvent
    self.name = UiUtility.nullEqualsNone(str(results[0].mFeature.attribute('road_name_body')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u014d' in position 1: ordinal not in range(128)

**Comment by SPlanzer** [comment]
Please Retest in 0.8.3

**Comment by Deb-Jones** [comment]
Tested 0.8.9.
Now able to select a road centreline with a macron.
Road name in message to API not macronated:
 "roadCentrelineId":366422,
            "roadName":"PÅ«rÄkaunui",
            "roadType":"Road",
Displays correctly on review queue.
Displays correctly when I info tool the accepted address point.
Displays correctly in the address_publish table.
Displays correctly in the address component table.

Acceptable.
