### ISSUE TITLE
Submit address - Water Routes

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#59]
Unable to submit an address for a water route. Python error.

Traceback (most recent call last):
  File "D:/Users/djjones.AD/.qgis2/python/plugins\aims\AimsUI\AimsClient\Gui\ChangeQueueWidget.py", line 119, in submitAddress
    self._controller.uidm.addAddress(self.feature, respId)
  File "D:\Users\djjones.AD.qgis2\python\plugins\aims\AimsUI\AimsClient\Gui\UiDataManager.py", line 129, in addAddress
    self.dm.addAddress(feature, respId)
  File "D:\Users\djjones.AD.qgis2\python\plugins\aims\AIMSDataManager\DataManager.py", line 201, in addAddress
    self._addressAction(address,ActionType.ADD,reqid)
  File "D:\Users\djjones.AD.qgis2\python\plugins\aims\AIMSDataManager\DataManager.py", line 212, in _addressAction
    self._queueAction(FeedRef((FeatureType.ADDRESS,FeedType.CHANGEFEED)), at, address)
  File "D:\Users\djjones.AD.qgis2\python\plugins\aims\AIMSDataManager\DataManager.py", line 271, in _queueAction
    self.ioq[feedref]['in'].put({atype:(aorg,)})
TypeError: 'NoneType' object has no attribute '__getitem__'

Python version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

QGIS version:
2.8.7-Wien Wien, 8a47921

Python path: ['D:/Users/djjones.AD/.qgis2/python/plugins\processing', 'D:\Users\djjones.AD\.qgis2\python\plugins\aims', 'G:/QGIS28/apps/qgis-ltr/./python', u'D:/Users/djjones.AD/.qgis2/python', u'D:/Users/djjones.AD/.qgis2/python/plugins', 'G:/QGIS28/apps/qgis-ltr/./python/plugins', 'C:\Program Files (x86)\ArcGIS\bin', 'G:\QGIS28\bin\python27.zip', 'G:\QGIS28\apps\Python27\DLLs', 'G:\QGIS28\apps\Python27\lib', 'G:\QGIS28\apps\Python27\lib\plat-win', 'G:\QGIS28\apps\Python27\lib\lib-tk', 'G:\QGIS28\bin', 'G:\QGIS28\apps\Python27', 'G:\QGIS28\apps\Python27\lib\site-packages', 'G:\QGIS28\apps\Python27\lib\site-packages\PIL', 'G:\QGIS28\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win32.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\python_dateutil-2.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\pytz-2014.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\win32', 'G:\QGIS28\apps\Python27\lib\site-packages\win32\lib', 'G:\QGIS28\apps\Python27\lib\site-packages\Pythonwin', 'G:\QGIS28\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win32.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\six-1.10.0-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', u'D:/Users/djjones.AD/.qgis2//python', '..', '.qgis2/python/plugins/AIMS_Plugin_threaded', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', 'D:\Users\djjones.AD\.qgis2\python\plugins\intramaps_qgis\ui', 'G:\QGIS28\apps\qgis-ltr\python\plugins\ElectoralAddressPlugin', 'G:\QGIS28\apps\qgis-ltr\python\plugins\fTools\tools', '.qgis2/python/plugins/AIMS_Plugin_threaded', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc']

**Comment by Deb-Jones** [comment]
Previous Issue resolved, new python error when submitting a water address:

Traceback (most recent call last):
  File "D:/Users/djjones.AD/.qgis2/python/plugins\aims\AimsUI\AimsClient\Gui\ChangeQueueWidget.py", line 119, in submitAddress
    self._controller.uidm.addAddress(self.feature, respId)
  File "D:\Users\djjones.AD.qgis2\python\plugins\aims\AimsUI\AimsClient\Gui\UiDataManager.py", line 129, in addAddress
    self.dm.addAddress(feature, respId)
  File "D:\Users\djjones.AD.qgis2\python\plugins\aims\AIMSDataManager\DataManager.py", line 201, in addAddress
    self._addressAction(address,ActionType.ADD,reqid)
  File "D:\Users\djjones.AD.qgis2\python\plugins\aims\AIMSDataManager\DataManager.py", line 212, in _addressAction
    self._queueAction(FeedRef((FeatureType.ADDRESS,FeedType.CHANGEFEED)), at, address)
  File "D:\Users\djjones.AD.qgis2\python\plugins\aims\AIMSDataManager\DataManager.py", line 272, in _queueAction
    self.notify(feedref)
  File "D:\Users\djjones.AD.qgis2\python\plugins\aims\AIMSDataManager\Observable.py", line 30, in notify
    observer.observe(_args, *_kwargs)
  File "D:\Users\djjones.AD.qgis2\python\plugins\aims\AIMSDataManager\DataSync.py", line 79, in observe
    self.client.processInputQueue(changelist)
  File "D:\Users\djjones.AD.qgis2\python\plugins\aims\AIMSDataManager\DataSync.py", line 353, in processInputQueue
    duref = self.processFeature(at,feature)
  File "D:\Users\djjones.AD.qgis2\python\plugins\aims\AIMSDataManager\DataSync.py", line 363, in processFeature
    self.duinst[ref].setup(self.etft,at,feature)
  File "D:\Users\djjones.AD.qgis2\python\plugins\aims\AIMSDataManager\DataUpdater.py", line 252, in setup
    self.payload = self.afactory.convertAddress(self.agobj,self.at)
  File "D:\Users\djjones.AD.qgis2\python\plugins\aims\AIMSDataManager\AddressFactory.py", line 117, in convertAddress
    raise AddressConversionException(msg)
AddressConversionException

Python version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

QGIS version:
2.8.7-Wien Wien, 8a47921

Python path: ['D:/Users/djjones.AD/.qgis2/python/plugins\processing', 'D:\Users\djjones.AD\.qgis2\python\plugins\aims', 'G:/QGIS28/apps/qgis-ltr/./python', u'D:/Users/djjones.AD/.qgis2/python', u'D:/Users/djjones.AD/.qgis2/python/plugins', 'G:/QGIS28/apps/qgis-ltr/./python/plugins', 'C:\Program Files (x86)\ArcGIS\bin', 'G:\QGIS28\bin\python27.zip', 'G:\QGIS28\apps\Python27\DLLs', 'G:\QGIS28\apps\Python27\lib', 'G:\QGIS28\apps\Python27\lib\plat-win', 'G:\QGIS28\apps\Python27\lib\lib-tk', 'G:\QGIS28\bin', 'G:\QGIS28\apps\Python27', 'G:\QGIS28\apps\Python27\lib\site-packages', 'G:\QGIS28\apps\Python27\lib\site-packages\PIL', 'G:\QGIS28\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win32.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\python_dateutil-2.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\pytz-2014.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\win32', 'G:\QGIS28\apps\Python27\lib\site-packages\win32\lib', 'G:\QGIS28\apps\Python27\lib\site-packages\Pythonwin', 'G:\QGIS28\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win32.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\six-1.10.0-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', u'D:/Users/djjones.AD/.qgis2//python', '..', '.qgis2/python/plugins/AIMS_Plugin_threaded', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', 'D:\Users\djjones.AD\.qgis2\python\plugins\intramaps_qgis\ui', 'G:\QGIS28\apps\qgis-ltr\python\plugins\ElectoralAddressPlugin', 'G:\QGIS28\apps\qgis-ltr\python\plugins\fTools\tools', '.qgis2/python/plugins/AIMS_Plugin_threaded', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc']

**Comment by SPlanzer** [comment]
this is pending API issue https://github.com/linz/AIMS/issues/70

**Comment by shane-turk-espatial** [comment]
@Deb-Jones @SPlanzer When submitting a water address is the road name and suburb information being passed to the API in the waterroutename and watername fields?

**Comment by SPlanzer** [comment]
@shane-turk-espatial  We are not providing a suburb but are suppling the centreline name against the WaterRoute . The API provides the following warning "RoadName must be provided"

Below is an example of the outgoing payload and response when submitting a water feature

**REQUEST**
{  
   'addressedObject':{  
      'addressPositions':[  
         {  
            'position':{  
               'crs':{  
                  'type':'name',
                  'properties':{  
                     'name':'urn:ogc:def:crs:EPSG::4167'
                  }
               },
               'type':'Point',
               'coordinates':[  
                  173.03893986971462,
                  -41.156239231394025
               ]
            },
            'positionType':'Unknown',
            'primary':True
         }
      ],
      'objectType':'Parcel'
   },
   'components':{  
      'addressNumber':'400',
      'addressType':'Water',
      'waterRoute':'Jackett Island',
      'roadCentrelineId':'330519',
      'lifecycle':u'Current'
   },
   'workflow':{  
      'sourceUser':'test.administrator'
   }
}

**RESPONSE**

str: 
{
    "class":[
        "error"
    ],
    "properties":{
        "status":400,
        "reason":"Bad Request",
        "message":"Validation Errors"
    },
    "entities":[
        {
            "class":[
                "validation"
            ],
            "rel":[
                "error"
            ],
            "properties":{
                "ruleId":"AIMS: A0001",
                "description":"RoadName must be provided",
                "severity":"Reject"
            }
        }
    ]
}

**Comment by Deb-Jones** [comment]
Tested 0.8.9

Created 37 Awaroa Bay. (entered number 37 and selected the RCL for Awaroa Bay). Upon submit an error popped up (preventing submit). "WaterName must be provided".

Created 39 Awaroa Bay. (entered number 39 and selected the RCL for Awaroa Bay, typed "Awaroa Bay" into the Water Name). Submitted successfully and approved successfully.

Created 41 Awaroa Bay. (entered number 41 and selected the RCL for Awaroa Bay, typed "Dunedin" into the Water Name - i.e. an incorrect water name.) Submitted successfully and approved successfully. Water Name recorded as "Dunedin", not corrected in any way.

**Comment by shane-turk-espatial** [comment]
@Deb-Jones  could I please get the REQUEST/RESPONSE similar to the example above for those addresses please.  I have changed the code here but do not want to commit until I have tested it.

**Comment by Deb-Jones** [comment]
@SPlanzer can you supply this to @shane-turk-espatial?

**Comment by SPlanzer** [comment]
Water requests and responses as requested. @shane-turk-espatial  and @Deb-Jones let me know if i missed anything here. 

Debs **example 2**. As she outlines above, I have sent a water request with a NUMBER, WATER ROUTE NAME and WATER NAME with the same name as the water route

**REQUEST (Payload)**
dict: {'addressedObject': {'addressPositions': [{'position': {'crs': {'type': 'name', 'properties': {'name': 'urn:ogc:def:crs:EPSG::4167'}}, 'type': 'Point', 'coordinates': [173.0378103575084, -41.15486143310001]}, 'positionType': 'Unknown', 'primary': True}], 'objectType': u'Parcel'}, 'components': {'addressType': u'Water', 'waterRoute': u'Jackett Island', 'addressNumber': u'119', 'lifecycle': u'Current', 'roadCentrelineId': u'330519', 'waterName': u'Jackett Island'}, 'workflow': {'sourceUser': 'test.administrator'}}

**RESPONSE**
dict: {u'entities': [], u'class': [u'addresschange'], u'links': [{u'href': u'http://devassgeo01:8080/aims/api/address/changefeed/5014801', u'rel': [u'self']}], u'properties': {u'changeType': u'Add', u'workflow': {u'submitterUserName': u'test.administrator', u'queueStatus': u'Submitted', u'submittedDate': u'2016-06-03', u'sourceOrganisation': u'e-Spatial'}, u'addressedObject': {u'addressPositions': [{u'position': {u'crs': {u'type': u'name', u'properties': {u'name': u'urn:ogc:def:crs:EPSG::4167'}}, u'type': u'Point', u'coordinates': [173.0378103575084, -41.15486143310001]}, u'positionType': u'Unknown', u'primary': True}], u'externalObjectId': u'3653502', u'objectType': u'Parcel'}, u'components': {u'addressType': u'Water', u'addressNumber': 119, u'roadCentrelineId': 330519, u'waterName': u'Jackett Island', u'waterRoute': u'Jackett Island', u'lifecycle': u'Current'}, u'changeId': 5014801}}

Debs **Example 3**. As she outlines above, I have sent a water request with a NUMBER, WATER ROUTE NAME and incorrect WATER NAME

**REQUEST (Payload)**
dict: {'addressedObject': {'addressPositions': [{'position': {'crs': {'type': 'name', 'properties': {'name': 'urn:ogc:def:crs:EPSG::4167'}}, 'type': 'Point', 'coordinates': [173.03885556546504, -41.155521469266375]}, 'positionType': 'Unknown', 'primary': True}], 'objectType': u'Parcel'}, 'components': {'addressType': u'Water', 'waterRoute': u'Jackett Island', 'addressNumber': u'111', 'lifecycle': u'Current', 'roadCentrelineId': u'330519', 'waterName': u'Dunedin'}, 'workflow': {'sourceUser': 'test.administrator'}}

**RESPONSE**
dict: {u'entities': [], u'class': [u'addresschange'], u'links': [{u'href': u'http://devassgeo01:8080/aims/api/address/changefeed/5014799', u'rel': [u'self']}], u'properties': {u'changeType': u'Add', u'workflow': {u'submitterUserName': u'test.administrator', u'queueStatus': u'Submitted', u'submittedDate': u'2016-06-03', u'sourceOrganisation': u'e-Spatial'}, u'addressedObject': {u'addressPositions': [{u'position': {u'crs': {u'type': u'name', u'properties': {u'name': u'urn:ogc:def:crs:EPSG::4167'}}, u'type': u'Point', u'coordinates': [173.03885556546504, -41.155521469266375]}, u'positionType': u'Unknown', u'primary': True}], u'externalObjectId': u'3653502', u'objectType': u'Parcel'}, u'components': {u'addressType': u'Water', u'addressNumber': 111, u'roadCentrelineId': 330519, u'waterName': u'Dunedin', u'waterRoute': u'Jackett Island', u'lifecycle': u'Current'}, u'changeId': 5014799}}

**Comment by shane-turk-espatial** [comment]
Thanks for the data.  The release is currently underway and cant be actioned until next week.

**Comment by rgabara** [comment]
TWG: @shane-turk-espatial , can you please update the status of this and assign to Deb for test if complete and deployed.

**Comment by shane-turk-espatial** [comment]
ready for testing.

Example 1 returns:
54;"AddressableobjectID was calculated as the externalID was not supplied";"AIMS: V0027"
34;"Suburb/Locality Name has been changed";"AIMS: V0008"

Example 2 returns:
54;"AddressableobjectID was calculated as the externalID was not supplied";"AIMS: V0027"

Example 3 returns:
54;"AddressableobjectID was calculated as the externalID was not supplied";"AIMS: V0027"
34;"Suburb/Locality Name has been changed";"AIMS: V0008"

**Comment by Deb-Jones** [comment]
Tested 23/6/16
1. If I attempt to add a water route address I get a pop-up error in the UI stating: WaterName must be provided.
2. If I attempt to edit a water route address Water Route Name is not populated, RCL_Id is populated. Water Name is populated.The feature layer does contain the water route name.
   I get a pop-up error in the UI stating: Please Supply a Water Route Name.
3. If I attempt to move a water route address I get a yellow band error in the UI stating: Incomplete Response: Layer data may not be complete.

**Comment by SPlanzer** [comment]
I have numbered the above and split into three issues

Please see 
1. is not #100 (question)
2. is now #99 (ready for retest)
3. is now #98 (ready for retest)

**Comment by SPlanzer** [comment]
Hi @Deb-Jones, I have split this issue here into several smaller issues. 

I feel this can be closed. Please close this if you are satisfied the new issues cover what is captured here.
