### ISSUE TITLE
Submit Addres - road suffix

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#60]
When I create an address on a road with a suffix, both the Road Prefix and the Road Suffix are being populated with the road Suffix.

e.g. Union Street West in Dunedin on before submit appears as:
Road Prefix: null
Road Name: Union
Road Type: Street
Road Suffix: West
Appears on resolution queue as:
Road Prefix: West
Road Name: Union
Road Type: Street
Road Suffix: West

Also, when I try to accept I get errors:
- Road Suffix has been changed
- RoadCentreLineID and Full Road name do not match.

Validation Rule 38 - road Suffix has been changed - AIMS: V0006 should be an info not a reject so should not appear at this point in the process.

Validation Rule 16 - road centrelineid and full road name do not match - AIMS: V0015 should be a warning not a reject so should not appear at this point in the process.

**Comment by SPlanzer** [comment]
Please retest in 0.8.1

**Comment by Deb-Jones** [comment]
Tested 0.8.1.

The review queue displays the correct road name in Full Road, but in the break down below it still shows West in the prefix field.

![image](https://cloud.githubusercontent.com/assets/15723101/15346246/1abbd00e-1d0a-11e6-8675-3bcde8b7f6a4.png)

The database is being updated correctly.
15898691;1787896;18;"Dunedin"
15898690;1787896;17;"North Dunedin"
15898689;1787896;14;"West"
15898688;1787896;13;"Street"
15898687;1787896;12;"Union"
15898686;1787896;9;"A"
15898685;1787896;8;"49"

Reduced priority to milestone 1.1 because functionally this is working.

**Comment by SPlanzer** [comment]
Please test again in 0.8.3

**Comment by Deb-Jones** [comment]
Tested 0.8.9, passed.
