### ISSUE TITLE
Managing Selection

### ISSUE THREAD

**Issue by LizStandley** [linz/QGIS-AIMS-Plugin#64]
5/5/16 - moved over from scrum board

**Comment by Deb-Jones** [comment]
The review queue selection gets dropped.

**Comment by SPlanzer** [comment]
please review in current version 0.8.9+

**Comment by Deb-Jones** [comment]
Tested in 0.8.9
The review queue is still jumping selections. It jumps every 4-9 seconds. (I timed it).

**Comment by SPlanzer** [comment]
??? I'll have to pay you a visit Tuesday. The symptoms you have mentioned have never been quite what I have seen. The selection is currently stable in both my environments (including opa) and when an item is accepted or declined the selection moves to the next line.

**Comment by Deb-Jones** [comment]
The process that triggers this to occur is for the user to sort the review queue by change order number in descending order, then select the top item. I think this is a process users will want to follow so that they can approve the changes they've just created.

**Comment by SPlanzer** [comment]
Please retest 0.8.10

**Comment by Deb-Jones** [comment]
Not getting dropped. Will reopen if it reoccurs but at the moment I consider it resolved.
