### ISSUE TITLE
Contextual Layers

### ISSUE THREAD

**Issue by LizStandley** [linz/QGIS-AIMS-Plugin#67]
5/5/16 - moved over from scrum board

**Comment by Deb-Jones** [comment]
Additional layers. e.g. lodged parcels.

**Comment by Deb-Jones** [comment]
Team UAT repeated the requirement for Lodged Parcels.

**Comment by linzbjones** [comment]
TWG - @Deb-Jones can you please confirm lodged parcels has been added? if we need other layers, can we please raise them as separate issues.

**Comment by Deb-Jones** [comment]
Lodged Parcels added.
