### ISSUE TITLE
Threading the UI

### ISSUE THREAD

**Issue by LizStandley** [linz/QGIS-AIMS-Plugin#68]
5/5/16 - moved over from scrum board

**Comment by Deb-Jones** [comment]
When QGIS becomes non-responsive.

**Comment by linzbjones** [comment]
TWG - @SPlanzer can you confirm if threading is complete and then close.

**Comment by SPlanzer** [comment]
Data Handling is multi threaded. Data monitoring runs in a thread outside the main thread.

Closed
