### ISSUE TITLE
Retire Address - Stacked Address

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#69]
When you retire a stacked address a warning pops up stating Conflict - AddressId has been updated by someone else. The retire still happens, so the message should not be appearing.

Assigned to milestone 1.1 because functionally the system still works so we could go live with this bug.

**Comment by SPlanzer** [comment]
The same address was getting retire multiple times due to selection model reporting selected rows twice. Hence the second time a stacked address is retired the conflict was raised. 

Selection Model updated. Please retests against AIMS-0.8.1

**Comment by Deb-Jones** [comment]
Tested 0.8.1.
No longer get the conflict warning.
