### ISSUE TITLE
Create New Address Form - Dock form

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#7]
Requirement: Dock the Create New Address from on the left of the screen clear of the map window.
This requirement wasn't advised prior to development and so wasn't developed.

**Comment by SPlanzer** [comment]
Lets park this until we implement the resolution and change feed widgets. it would be good to see the amount of screen real estate these require. One solution maybe to add this to the tab cluster that the res/change-feed widgets will be a part of.

**Comment by Deb-Jones** [comment]
0.7.2 Form now docked.
