### ISSUE TITLE
Update Lifecycle - current to proposed

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#71]
You can't update a lifecycle from current to proposed. Validation Rule 47 - LifeCycle for an Update cant be changed from Current to Proposed - AIMS: V0023 - Reject.

The issue is that when a user tries to do this, an error message pops up and you lose your whole edit. It would be better if you were able to amend your edit and resubmit.

**Comment by SPlanzer** [comment]
Warning shown and update not submitted.

Please test in Release 0.8.2

**Comment by Deb-Jones** [comment]
Tested 0.8.2

Warning is given and opportunity given to change the lifecycle.
