### ISSUE TITLE
Retire Address - Python Error

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#79]
Testing 0.8.9
1. Select the retire address tool.
2. Click on an existing address.
3. Pop up saying address will be retired. Click OK.

The retire appears on the change queue.
The address is shown on the map as a pending retire.
A python error displays.
1. Accept retire.

The point disappears from the map.
The retire disappears from the change queue.
A row is added to the address_publish table for retired.
The previous row is updated in the address_publish table to latest = f.

So, functionally working correctly. Should not get the python error.
Assigned version 1.1 because we could go live with it, but we want it fixed.

Traceback (most recent call last):
  File "D:/Users/djjones/.qgis2/python/plugins\aims\AimsUI\AimsClient\Gui\ReviewQueueWidget.py", line 166, in featureSelected
    self.setMarker(self.uidm.reviewItemCoords(self.currentGroup, self.currentFeatureKey))
  File "D:\Users\djjones.qgis2\python\plugins\aims\AimsUI\AimsClient\Gui\UiDataManager.py", line 409, in reviewItemCoords
    pos = obj.meta.entities[0].getAddressPositions()[0]._position_coordinates
IndexError: list index out of range

Python version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

QGIS version:
2.8.7-Wien Wien, 8a47921

Python path: ['D:/Users/djjones/.qgis2/python/plugins\processing', 'D:\Users\djjones\.qgis2\python\plugins\aims', 'G:/QGIS28/apps/qgis-ltr/./python', u'D:/Users/djjones/.qgis2/python', u'D:/Users/djjones/.qgis2/python/plugins', 'G:/QGIS28/apps/qgis-ltr/./python/plugins', 'C:\Program Files (x86)\ArcGIS\bin', 'G:\QGIS28\bin\python27.zip', 'G:\QGIS28\apps\Python27\DLLs', 'G:\QGIS28\apps\Python27\lib', 'G:\QGIS28\apps\Python27\lib\plat-win', 'G:\QGIS28\apps\Python27\lib\lib-tk', 'G:\QGIS28\bin', 'G:\QGIS28\apps\Python27', 'G:\QGIS28\apps\Python27\lib\site-packages', 'G:\QGIS28\apps\Python27\lib\site-packages\PIL', 'G:\QGIS28\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win32.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\python_dateutil-2.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\pytz-2014.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\win32', 'G:\QGIS28\apps\Python27\lib\site-packages\win32\lib', 'G:\QGIS28\apps\Python27\lib\site-packages\Pythonwin', 'G:\QGIS28\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win32.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\six-1.10.0-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', u'D:/Users/djjones/.qgis2//python', '..', '.qgis2/python/plugins/AIMS_Plugin_threaded', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', 'D:\Users\djjones\.qgis2\python\plugins\intramaps_qgis\ui', 'G:\QGIS28\apps\qgis-ltr\python\plugins\ElectoralAddressPlugin', 'G:\QGIS28\apps\qgis-ltr\python\plugins\fTools\tools', '.qgis2/python/plugins/AIMS_Plugin_threaded', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc']

**Comment by SPlanzer** [comment]
Please retest in 0.8.10

**Comment by Deb-Jones** [comment]
Tested in 0.8.10.

Traceback (most recent call last):
  File "D:/Users/djjones/.qgis2/python/plugins\aims\AimsUI\AimsClient\Gui\ReviewQueueWidget.py", line 215, in featureSelected
    self.uQueueEditor.currentFeatureToUi(self.currentReviewFeature())
  File "D:/Users/djjones/.qgis2/python/plugins\aims\AimsUI\AimsClient\Gui\QueueEditorWidget.py", line 80, in currentFeatureToUi
    UiUtility.featureToUi(self)
  File "D:/Users/djjones/.qgis2/python/plugins\aims\AimsUI\AimsClient\Gui\UiUtility.py", line 230, in featureToUi
    posType = self.feature.meta.entities[0]._addressedObject_addressPositions[0]._positionType
IndexError: list index out of range

Steps to recreate:
1. Select Delete AIMS Feature tool.
2. Click on an existing address.
3. On pop-up, select OK.
4. Highlight/select change on review queue.

The address still deletes.

Note, if you don't accept or decline the change (i.e. leave it on the queue), subsequent selections of the change do not generate this message.

**Comment by SPlanzer** [comment]
Please retest on 0.8.11

**Comment by Deb-Jones** [comment]
Closed pending testing

**Comment by Deb-Jones** [comment]
Passed.
