### ISSUE TITLE
Create New Address Form - disallow multiple open forms

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#8]
Requirement: The user should only be able to open one New Address Form at a time.
This requirement was not specified prior to development and has not been developed.

**Comment by SPlanzer** [comment]
Implemented - please test in next version

**Comment by Deb-Jones** [comment]
User is still able to open multiple New Address Forms.

**Comment by Deb-Jones** [comment]
Tested 14/4/16 - Only one form opens.
