### ISSUE TITLE
Appellation

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#80]
Testing 0.8.9

Appellation no longer gets passed to API.

**Comment by SPlanzer** [comment]
Please retest in next 0.8.10

**Comment by Deb-Jones** [comment]
Tested.

The appellation is now passed to the API from the UI.

**Comment by Deb-Jones** [comment]
The appellation is being saved in the change_addressable_object table, but it isn't being bought back into the UI. So it's not there for the move, meaning that it gets deleted by any edit. It's also not there in the feature layer when you infotool it.

Is it not available in the API (meaning that I should raise an API issue), or is the UI just not pulling it in?

**Comment by Deb-Jones** [comment]
Problem 1 - I'll create a new issue in the AIMS repository because this is a DB/API issue.

For existing addresses with an appellation:
Appellation is recorded in aims_stage.change_addressable_object
![image](https://cloud.githubusercontent.com/assets/15723101/16287022/5cd79ce8-3934-11e6-80cd-c62a9f4d953e.png)
Appellation is not a field in the aims_stage.address_publish table.

http://tstassgeo02.ad.linz.govt.nz:8080/aims/api/address/features/2005873 does not list the appellation.
Therefore, the appellation does not display in the UI, and is not available for the UI when making an edit.

Problem 2 - This is a UI issue and still needs resolving.

When adding an appellation during an edit (i.e. there was no appellation, I'm editing features and typing in an appellation):
The appellation does not appear in http://tstassgeo02.ad.linz.govt.nz:8080/aims/api/address/resolutionfeed/3524582

**Comment by SPlanzer** [comment]
Typo in changefeed update template for appellation 

Resolved, Please retest in 0.8.11

**Comment by e-spatial** [comment]
The appellation field should be in the resolutionfeed, test https://github.com/linz/AIMS/blob/master/src/integration-test/test-cases/api/20_address/10_add_road_allfields/08-resolutionfeed-Get-OK.txt checks this.   It's here for the reviewer to see all information provided by the submitter.  We can re-test this if required.

Re-Problem 1 - 
a). The appellation is not in the address_publish table as the appellation is not published by AIMS.  We would only put it in if we are to publish it.

b). The features service does not have the appellation field, the purpose was for map display, all address details are supplied in the resolutionfeed for the reviewer and we would expect the UI to use this.

Re-Problem 2 -  
Looks like the update resolutionfeed test doesn't include the appellation field so we will add it in and retest to check the API is working for this.  Let us know the results of retesting 0.8.11.

**Comment by Deb-Jones** [comment]
Unable to test because issue https://github.com/linz/QGIS-AIMS-Plugin/issues/115 will remove appellation from the UI.
