### ISSUE TITLE
Address Data Position Descriptions

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#83]
Current address data positions in the drop down of the Edit Feature form include:

1 = Centroid
2 = Label
3 = Set Back off Road
4 = Unknown

AS/NZS 4819:2011 has the following types:
![image](https://cloud.githubusercontent.com/assets/15723101/15878138/b3423f94-2d6c-11e6-9a3e-4065ac14e768.png)

The values in the drop down should be updated to include:

Building centroid
Parcel centroid (4819 specifies property centroid but this description doesn't match what we're actually doing).
Building access point
Frontage centre setback
Driveway frontage
Unknown (for migrated addresses and TA supplied spatial addresses where actual position type is unknown).

This is dependant on issue https://github.com/linz/AIMS/issues/98 because it will need implementing in the database and API for it to work in the UI.

**Comment by Deb-Jones** [comment]
@billgeo 

https://github.com/linz/AIMS/issues/98 now implemented and tested.

Will https://github.com/linz/AIMS/issues/99 be implemented, or should @SPlanzer hardcode the values into the UI?

Note, if Issue 99 is implemented Simon will still have to edit the UI because the API would be serving up data differently.

**Comment by billgeo** [comment]
@Deb-Jones if it's a small piece of work for @SPlanzer to hardcode the extra ones in then I would suggest we are fine to do that for now.

**Comment by billgeo** [comment]
@SPlanzer - if this is effort/small then proceed.

**Comment by SPlanzer** [comment]
Combobox now includes exclusively the below:

'Unknown',
'Building centroid',
'Parcel centroid',
'Building access point',
'Frontage centre setback',
'Driveway frontage'

**Comment by Deb-Jones** [comment]
Sorry Simon, I didn't update this issue with changes made on the database issue. Values should include:

[addresspositiontype.txt](https://github.com/linz/QGIS-AIMS-Plugin/files/358178/addresspositiontype.txt)

**Comment by SPlanzer** [comment]
Updated to include a subset of the addresspositiontype.txt contents as discussed with @Deb-Jones 

'Unknown', 'Property Centroid', 'Unit Centroid', 'Frontage Centre Set Back', 'Building Centroid',
                                     'Property Access Point Set Back', 'Building Access Point', 'Front Door Access'

**Comment by Deb-Jones** [comment]
Tested 0.8.16 Passed
