### ISSUE TITLE
Estimate effort for high priority issues

### ISSUE THREAD

**Issue by billgeo** [linz/QGIS-AIMS-Plugin#87]
@SPlanzer, am adding these effort labels. If you are in on Friday can you review please?

Roughly use this as a guideline, but don't get too caught up in trying to make it accurate.

small = < 2 hours
medium = 2 - 8 hours
large = > 8 hours

**Comment by SPlanzer** [comment]
On Tuesday @Deb-Jones , @linzbjones  and I went over all open issue in this repo and reassessed these. 

Acting on this ticket only three issues that are of milestone 1.0 were without effort labels. All of these are with deb to retest and have now been  given  "effort/small"
