### ISSUE TITLE
Map - Road Name

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#9]
Road names are not displaying accurately on the map. The type of "Road" is being appended to all roads.
This is not a requirement of the first sprint but will require fixing in a later sprint.

**Comment by SPlanzer** [comment]
Implemented - please test in next version

**Comment by Deb-Jones** [comment]
Road name type is now displaying correctly.

**Comment by Deb-Jones** [comment]
Streets without a road type are not appearing at all. e.g. The Terrace, The Quarterdeck, The Drive.

**Comment by SPlanzer** [comment]
fixed - done some quick testing. Looks fine

**Comment by Deb-Jones** [comment]
Tested 14/4/2016 - fixed.
