### ISSUE TITLE
Temporary Features not labelled 

### ISSUE THREAD

**Issue by SPlanzer** [linz/QGIS-AIMS-Plugin#92]
When a users successfully accepts a changefeed item the UI creates a temporary published feature item based on the API response. There is no full address number label in this response.

Currently the layer employs the Qgis Label Builder to compile a full number label from individual components. However this is failing when Qvariants Null Values are mapped to the layer. 

There are several options to solve this and when I pick up this issue I will asses these then:
- Resolve Qvariant Null matching in label expression
- Remove map temp features Qvaraints to None or other

This problem is not label as high priority as it only affects temp features and when the Data Manager supplies a refresh to the feature layer the feature is labelled

**Comment by SPlanzer** [comment]
Please retest in 0.8.13

**Comment by Deb-Jones** [comment]
Tested 0.8.16 Passed.
