### ISSUE TITLE
Test creating a new user

### ISSUE THREAD

**Issue by SPlanzer** [linz/QGIS-AIMS-Plugin#93]
Create a new user from start to finish. 
- Add the user to the tomcat config
- Add the user to AIMS Via the API
- Ensure the user has an AD login and is assigned to the AIMS reader Role

Document

**Comment by rgabara** [comment]
TWG: Subtask: Ben to add this test to the UAT test plan

**Comment by SPlanzer** [comment]
Passed and Closed

Will document the process for creating a new user. An issue/task has been created to track this (#96)
