### ISSUE TITLE
Change QGIS Test User Account

### ISSUE THREAD

**Issue by e-spatial** [linz/QGIS-AIMS-Plugin#94]
Change the user account being used for QGIS testing to prevent conflict with the test.administrator user as this user is used by the integration test harness and prevents test data being successfully removed by the test harness once tests are completed.

**Comment by SPlanzer** [comment]
I have setup user logins for all testers. I will tell those who have in the past used test.administrator (@Deb-Jones, @josephramsay) to switch to the new logins.

Closed
