### ISSUE TITLE
Editng water features fails

### ISSUE THREAD

**Issue by SPlanzer** [linz/QGIS-AIMS-Plugin#99]
issue split from #59

If I attempt to edit a water route address Water Route Name is not populated, RCL_Id is populated. Water Name is populated.The feature layer does contain the water route name.
I get a pop-up error in the UI stating: Please Supply a Water Route Name.

**Comment by SPlanzer** [comment]
Water Route Name is now consistently populated - This can be retested in 0.8.11

**Comment by Deb-Jones** [comment]
Closed pending testing

**Comment by Deb-Jones** [comment]
Original error remedied. New error recorded on https://github.com/linz/QGIS-AIMS-Plugin/issues/121
